TencentBlueKing/bk-iam-saas

- docs/CONTRIBUTING.md
- readme.md
- readme_en.md
- mod docs: bk-iam-app to bk-iam-saas
- Fixes #
> mod docs: bk-iam-app to bk-iam-saas

- docs/ISSUE_TEMPLATE.md
- frontend/build/dev-server.js
- frontend/build/paas-server.js
- readme.md
- readme_en.md
> update readme and some annotation

- frontend/src/views/system-access/registry/index.vue
- frontend/src/views/system-access/registry/resource-type-sideslider.vue
> 勾选bug，资源类型保存问题解决

- saas/poetry.lock
- saas/pyproject.toml
- saas/requirements.txt
- saas/requirements_dev.txt
> chore(requirements.txt): update requirements version for security

- saas/backend/apps/group/tasks.py
- backend/apps/group/tasks.py
- Fixes #
> fix(backend/apps/group/tasks.py): group auth ignore path

- saas/config/default.py
> perf(config/default.py): update expired remind email task to 11am

- frontend/package.json
> fix: remove useless code

- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- update: 申请自定义权限参数由 tid 改为 cache_id
> update: 申请自定义权限参数由 tid 改为 cache_id

- saas/backend/component/resource_provider.py
- https://github.com/TencentBlueKing/bk-iam-saas/issues/20
> feat(resource provider): optimize the error message prompt

- saas/backend/biz/policy.py
- saas/tests/biz/policy_tests.py
- PolicyBeanList sub 方法, 处理未关联资源实例的操作与任意条件时的问题
- Fixes #
> fix: bugfix policy_list sub method with unrelated or any condition error

- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- fix: 修复无权限跳转过来, 新增的操作过期时间为 0 时，提交后权限过期的问题
> fix: 修复无权限跳转过来, 新增的操作过期时间为 0 时，提交后权限过期的问题

- frontend/package.json
> fix: update npm to 6.14.6

- frontend/src/views/approval-process/common/render-process-item.vue
- frontend/src/views/approval-process/components/custom-perm-process.vue
- frontend/src/views/approval-process/components/join-group-process.vue
- frontend/src/views/perm-template/components/render-content.vue
- fix: fixed approval-process select bugs
- fix: 修复未选择任何权限可保存为推荐权限模板
> 修复权限模板&审批流程bug

- frontend/src/views/group/detail/group-perm-new.vue
- frontend/src/views/perm/components/render-group-perm-sideslider.vue
> 添加我的分级管理员部分注释

- saas/backend/component/iam.py
- saas/backend/component/usermgr.py
- saas/backend/service/policy/query.py
- 调用用户管理的所有API都调整为分页拉取方式
- 删除无用代码 - 查询后端策略表达式
- https://github.com/TencentBlueKing/bk-iam-saas/issues/86
> Ft remove no page usermgr api

- saas/backend/api/authorization/mixins.py
- saas/backend/biz/policy.py
- saas/backend/service/policy/query.py
- 优化授权API性能
- https://github.com/TencentBlueKing/bk-iam-saas/issues/91
> perf(auth api): list subject policy from actions

- frontend/src/views/approval-process/common/render-process-item.vue
- frontend/src/views/approval-process/components/custom-perm-process.vue
- frontend/src/views/approval-process/components/join-group-process.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/perm-template/components/render-content.vue
> 修复从配置平台跳转到权限中心无法选择bug

- frontend/src/views/apply/components/apply-create-rate-manager-detail.vue
- frontend/src/views/apply/index.vue
- frontend/src/views/grading-admin/components/add-action-sideslider.vue
- frontend/src/views/grading-admin/components/render-instance-detail-table.vue
- frontend/src/views/grading-admin/detail/index.vue
- frontend/src/views/grading-admin/edit/index.vue
- frontend/src/views/group/detail/group-perm-new.vue
- frontend/src/views/perm/components/render-group-perm-sideslider.vue
- saas/backend/biz/template.py
> refactor: 添加我的申请注释

- frontend/src/views/perm-apply/apply-join-user-group/index.vue
> fix: 修复分享链接带上条件过滤bug

- frontend/src/views/group/common/render-perm-item-new.vue
- frontend/src/views/group/detail/group-perm-new.vue
> refactor: 申请加入用户组添加注释

- frontend/package.json
- chore: postinstall => add-husky
> chore: postinstall => add-husky

- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
> refactor: 添加申请自定义权限选择操作注释

- saas/build/v3/app_desc.yaml
> fix: fix v3 build app_desc.yaml env_variables

- saas/backend/api/management/views/group.py
> fix(mgmt api): creat group bind role wrong

- saas/backend/trans/open_management.py
- 修复管理类API创建分级管理员时授权范围没有按照系统聚合导致后续授权问题
- Fixes #
> Ft mgmt api create rating manage

- frontend/src/model/instance.js
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- refactor: 权限申请-资源实例逻辑梳理、添加注释
> refactor: 权限申请-资源实例逻辑梳理、添加注释

- frontend/src/components/header/index.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
> fix: 普通用户没有任何分级管理员时无法注销问题 #149

- frontend/src/views/perm/components/perm-table-edit.vue
- frontend/src/views/perm/custom-perm/index.vue
- frontend/src/views/perm/group-perm/index.vue
- frontend/src/views/perm/index.vue
- feat: myPerm 模块添加 data-test-id
> feat: myPerm 模块添加 data-test-id

- saas/backend/biz/policy.py
- policy_change_lock retrun
- Fixes #
> fix: bugfix policy_change_lock

- saas/backend/apps/subject/views.py
- subject policy partial delete bugfix
- Fixes #
> fix: subject policy partial delete bugfix

- saas/backend/biz/application.py
> fix(application): custom application not approver

- saas/backend/apps/user/tasks.py
> fix(backend/apps/user/tasks.py): bugfix clean expired policy

- saas/backend/api/authorization/serializers.py
- saas/backend/api/management/serializers.py
- saas/backend/apps/application/base_serializers.py
- saas/backend/apps/policy/serializers.py
- 修复资源实例名称由于drf slz行为被默认trim的问题
- Fixes #
> fix(resource): name trim for drf slz

- saas/backend/component/esb.py
- saas/blueking/component/conf.py
- saas/build/v3/app_desc.yaml
- saas/config/prod.py
- mod esb url setting for v3 smart
- Fixes #
> mod esb url settings

- saas/resources/templates/group_expired_mail.html
- saas/resources/templates/user_expired_mail.html
> fix: 续期邮件企业微信链接显示问题 #158

- frontend/src/views/perm-apply/components/resource-instance-table.vue
- isChanged status should add user.timestamp
> isChanged status should add user.timestamp

- frontend/src/components/choose-ip/resource-select.vue
- frontend/src/views/group/detail/group-perm-new.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/components/render-resource.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/perm/components/render-group-perm-sideslider.vue
> refactor: checkbox 选中时逻辑梳理

- frontend/src/views/group/common/render-template-item.vue
> refactor: modify isUser

- frontend/index.html
- saas/backend/common/vue.py
> fix: fix frontend component api url

- saas/backend/biz/policy.py
> fix(backend/biz/policy.py): fix ignore_path

- saas/backend/api/authorization/mixins.py
- saas/backend/biz/policy.py
- 所有授权API 添加检查资源实例是否超限
- 所有授权API 对Admin用户授权默认忽略
> Ft grant open api add limit

- saas/backend/apps/policy/views.py
- saas/backend/biz/policy.py
- saas/backend/biz/policy_tag.py
- saas/tests/biz/policy_tests.py
> Feat apply policy

- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/perm-template/components/render-content.vue
- fix: Super admin commonActions are empty #91071575
> fix: Super admin commonActions are empty #91071575

- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- fix: 取消勾选对应权限的实例报错 #92356085
> fix: 修复取消勾选对应权限的实例报错的bug

- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
> optimize the code

- saas/backend/api/authorization/mixins.py
- saas/backend/api/authorization/views/resource.py
- saas/backend/api/authorization/views/resource_creator_action.py
- saas/backend/biz/policy.py
- 所有授权接口返回策略信息里包含统计相关信息，目前包括策略里已授权的资源实例数量
- Fixes #
> feat(auth api): all api return policy with statistics

- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
> 修复后台关联数据时tag返回值bug

- saas/backend/apps/group/tasks.py
- saas/backend/apps/template/tasks.py
- saas/backend/apps/template/views.py
- saas/backend/biz/group.py
- saas/backend/long_task/tasks.py
- saas/config/default.py
- 重试长时间pending/running的任务
- Fixes #
> feat: retry long task

- frontend/src/views/approval-process/components/join-group-process.vue
> fix: 修复用户组审批流程显示为空的bug

- saas/backend/apps/organization/models.py
- saas/backend/apps/organization/tasks.py
- saas/backend/util/cache.py
- 修复Redis有问题时，Redis Cache一直block的问题
- Fixes #
> fix(redis cache): cmd block when redis error

- saas/backend/util/cache.py
> fix(redis connect args): spell wrong

- saas/backend/apps/organization/managers.py
- saas/backend/apps/organization/tasks.py
> fix(organization): sync record log error

- saas/backend/apps/organization/serializers.py
- saas/backend/apps/organization/views.py
> refactor(organization): error log display

- saas/backend/apps/organization/filters.py
- saas/backend/apps/organization/tasks.py
- saas/backend/apps/organization/views.py
- 增加时间过滤 用以筛选同步日志
https://github.com/TencentBlueKing/bk-iam-saas/issues/200
> feature: 组织架构同步记录展示 #200

- saas/backend/component/iam.py
- saas/config/default.py
- 支持通过apigateway调用iam后台
- Fixes #304
> feat(component): support call iam backend via apigateway

- saas/backend/component/http.py
- saas/backend/component/resource_provider.py
- saas/backend/metrics/__init__.py
- 增加外部依赖component的metrics
- 增加接入系统回调的metrics
- Fixes #203
> feat(metrics): add metrics for component and resource_provider

- frontend/src/views/group/components/add-group-perm-sideslider.vue
- frontend/src/views/perm-template/components/render-action.vue
Reverts TencentBlueKing/bk-iam-saas#371
> Revert "add tips"

- saas/backend/component/http.py
- saas/backend/component/iam.py
- saas/backend/component/resource_provider.py
- saas/backend/util/cache.py
- saas/poetry.lock
- saas/pyproject.toml
- poetry: add pytest-cov
- 
- Fixes #
> build(poetry): add pytest-cov

- saas/backend/apps/group/audit.py
- saas/backend/apps/policy/tasks.py
- 修复审计日志错误问题
- 修复Action模型删除事件处理异常问题
- Fixes #
> Fix some tiny error

- saas/backend/apps/organization/migrations/0004_auto_20201230_1653.py
- saas/backend/apps/role/migrations/0008_auto_20201230_1653.py
- 解决migrate时依赖esb的问题
- Fixes #
> Ft resolve migrate depend esb

- saas/backend/apps/group/serializers.py
- saas/backend/apps/role/serializers.py
- saas/backend/apps/role/views.py
> fix(update renamed resource): role and group update error

- saas/backend/common/local.py
- saas/backend/component/resource_provider.py
- 回调接入系统，支持传递请求时的用户信息
- Fixes #
> feat(resource provider): support request username param

- saas/backend/apps/template/views.py
- saas/backend/biz/group.py
- saas/backend/long_task/tasks.py
> fix: update TaskFactory synchronous execution

- frontend/src/views/approval-process/components/join-group-process.vue
- frontend/src/views/grading-admin/edit/index.vue
- frontend/src/views/group/add-perm/index.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/perm/components/perm-table-edit.vue
- frontend/src/views/perm/components/render-detail-edit.vue
> feat: 完善笛卡尔功能 #0

- frontend/src/views/grading-admin/create/index.vue
- frontend/src/views/group/create/index.vue
> fix： 用户组新建权限bugs

- frontend/src/model/template-sync-policy.js
- frontend/src/views/perm-template/edit/difference.vue
- frontend/src/views/perm-template/edit/sync.vue
> fix: 修复编辑权限模板bug

- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/group/components/preview-resource-dialog.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/user/components/perm-table-edit.vue
> fix: 修复预和删除的bug

- frontend/src/views/grading-admin/create/index.vue
- frontend/src/views/grading-admin/edit/index.vue
- frontend/src/views/group/add-perm/index.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/group/create/index.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
> fix: 修复组权限选中时的bug

- frontend/src/language/lang/en.js
- frontend/src/language/lang/zh.js
- frontend/src/views/perm/index.vue
- feat: add permTransfer button
> feat: add permTransfer button #0

- frontend/src/views/perm-apply/components/resource-instance-table.vue
> fix 自定义权限申请bug

- frontend/src/views/perm-apply/components/resource-instance-table.vue
> fix: fix 申请期限bugs

- saas/backend/apps/policy/urls.py
- saas/backend/apps/policy/views.py
- saas/backend/biz/policy.py
- saas/backend/service/models/policy.py
- saas/tests/biz/policy_tests.py
> feat: add delete by resource group id api

- saas/backend/apps/subject/urls.py
- saas/backend/apps/subject/views.py
> feat: add subject policy resource group delete api

- saas/backend/apps/subject/views.py
> fix: fix doc

- frontend/src/model/policy.js
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/components/resource-instance-table.css
- frontend/src/views/perm-apply/components/resource-instance-table.vue
> Poloo develop

- saas/backend/apps/policy/serializers.py
> fix: fix int value rang

- saas/poetry.lock
- saas/pyproject.toml
- saas/requirements.txt
- saas/requirements_dev.txt
> fix: lock typing-extensions 3.7.4.3

- saas/backend/service/engine.py
> fix: fix group engine

- saas/poetry.lock
- saas/pyproject.toml
- saas/requirements.txt
- saas/requirements_dev.txt
> fix: lock lock typing-extensions 3.7.4.3

- frontend/src/views/transfer/history-detail.vue
- frontend/src/views/transfer/history.vue
> feat: 权限交接

- frontend/src/views/group/components/render-instance-table.vue
> fix: fix bugs

- saas/backend/api/management/migrations/0004_auto_20211130_1137.py
- saas/backend/common/renderers.py
- saas/backend/tracing/__init__.py
- saas/backend/tracing/apps.py
- saas/backend/tracing/instrumentor.py
- saas/backend/tracing/setup.py
- saas/config/default.py
- saas/poetry.lock
- saas/pyproject.toml
> Ft tracing

- saas/resources/apigateway/bk_apigw_resources_bk-iam.yaml
> fix(apigw/configs): bugfix delete action policies url wrong

- saas/backend/apps/approval/migrations/0002_auto_20201217_1045.py
- saas/backend/apps/handover/migrations/0001_initial.py
- saas/backend/component/resource_provider.py
- saas/config/default.py
> fix(resource_provider): refine the message of callback api fail

- saas/config/default.py
> fix: config add enable_permission_handover

- saas/build/v3/Aptfile
- add build-essential in aptfile
- Fixes #
> build(v3/build): add build-essential in aptfile

- saas/backend/apps/role/serializers.py
- saas/backend/biz/permission_audit.py
- saas/backend/component/engine.py
- saas/backend/service/engine.py
> 查询有权限的subject

- frontend/src/views/resource-permiss/index.vue
- add searchType === 'operate'
> fix add searchType === 'operate'

- frontend/src/views/resource-permiss/index.vue
> fix: modify text height

- frontend/src/views/transfer/components/perm-table.vue
- frontend/src/views/transfer/components/render-depart-perm-sideslider.vue
- frontend/src/views/transfer/components/render-detail-edit.vue
- frontend/src/views/transfer/components/render-detail.vue
- frontend/src/views/transfer/components/render-group-perm-sideslider.vue
- frontend/src/views/transfer/components/render-member.vue
- frontend/src/views/transfer/components/render-renewal-table.vue
- frontend/src/views/transfer/components/render-template-perm-sideslider.vue
- frontend/src/views/transfer/custom-perm-table.vue
- frontend/src/views/transfer/custom.vue
- frontend/src/views/transfer/group.vue
Reverts TencentBlueKing/bk-iam-saas#592
> Revert "fix: 过期的自定义权限也可以交接的问题"

- saas/build/v3/bin/sync_apigateway.sh
- 修复 APIGateway同步脚本中目录错误
- Fixes #
> fix(build/apigateway): bugfix build/v3/bin/sync_apigateway.sh dir wron

- saas/config/default.py
- 修复配置中从环境获取网关访问地址(BK_API_URL_TMPL)
- Fixes #
> fix(config/default): fix BK_API_URL_TMPL  get from env

- frontend/src/views/transfer/custom.vue
> fix: 过期的自定义权限也可以交接的问题

- saas/backend/common/error_codes.py
- saas/backend/component/engine.py
- saas/backend/component/esb.py
- saas/backend/component/iam.py
> fix(esb/error): fix call esb api error message without details

- frontend/src/views/set/components/render-super-manager.vue
> fix: delete console.log

- frontend/src/views/transfer/custom-perm-table.vue
- frontend/src/views/transfer/custom.css
> feat: 自定义权限交接适配笛卡尔积数据结构

- saas/backend/api/authorization/audit.py
> fix: fix admin grant api audit

- frontend/src/views/perm-apply/components/sideslider-effect-time.vue
> fix: fix select bugs

- saas/backend/common/error_codes.py
- 错误消息增加 code_name, 有利于问题排查使用关键字进行检索
- Fixes #
> feat/error_code: add code_name into error message

- frontend/src/views/perm-apply/components/resource-instance-table.css
- frontend/src/views/perm-apply/components/resource-instance-table.vue
> feat: add line

- saas/backend/service/utils/environment.py
- saas/tests/service/translate_tests.py
- fix environment translate
- Fixes #
> fix: fix environment translate

- frontend/src/views/apply/components/sideslider-effect-condition.vue
- frontend/src/views/group/components/effect-condition-detail.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/group/components/sideslider-effect-condition.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/perm-apply/components/sideslider-effect-time.vue
- frontend/src/views/perm/custom-perm/sideslider-effect-condition.vue
> 修复用户组选择多组实例bug

- saas/backend/component/http.py
- saas/blueking/component/base.py
> feat: add component slow request log

- frontend/src/views/grading-admin/components/render-instance-table.vue
> fix: hot fix bugs

- readme.md
- readme_en.md
> docs(readme.md): add bk-iam-cli link

- frontend/src/views/group/add-perm/index.vue
> fix: 修复已选择实例下方还提示错误信息

- frontend/src/views/grading-admin/components/render-instance-table.vue
> fix: add code

- frontend/src/components/system-log/index.vue
- frontend/src/views/perm/index.vue
- frontend/src/views/transfer/index.vue
> update: 修改权限交接历史入口位置

- saas/backend/apps/organization/serializers.py
- saas/backend/apps/organization/urls.py
- saas/backend/apps/organization/views.py
- saas/backend/apps/system/serializers.py
- saas/backend/apps/system/views.py
- saas/backend/biz/application_process.py
- saas/backend/biz/related_policy.py
- saas/backend/biz/template.py
> Ft user dept

- saas/backend/component/resource_provider.py
- 修复 resource_provider 异常f-string拼接错误
- Fixes #
> fix(resource_provider/exception): fix exception f-string fail

- frontend/src/components/choose-ip/topology-tree.vue
- frontend/src/components/header/index.vue
- frontend/src/components/nav/index.vue
- frontend/src/views/grading-admin/components/add-action-sideslider.vue
- frontend/src/views/grading-admin/components/basic-info.vue
- frontend/src/views/grading-admin/components/render-member.vue
- frontend/src/views/grading-admin/create/index.vue
- frontend/src/views/grading-admin/index.vue
- frontend/src/views/group/add-perm/index.vue
- frontend/src/views/group/common/iam-confirm-dialog.vue
- frontend/src/views/group/components/add-action-sideslider.vue
- frontend/src/views/group/components/add-group-perm-sideslider.vue
- frontend/src/views/group/components/basic-info.vue
- frontend/src/views/group/components/iam-add-member.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/group/create/index.vue
- frontend/src/views/group/index.vue
- frontend/src/views/perm-template/components/render-action.vue
- frontend/src/views/perm-template/components/render-content.vue
- frontend/src/views/perm-template/index.vue
- frontend/src/views/perm/custom-perm/custom-perm-table.vue
- frontend/src/views/perm/group-perm/index.vue
- frontend/src/views/set/components/render-system-manager.vue
- frontend/src/views/set/index.vue
> feat: add data-test-id

- frontend/.eslintrc.js
> feat: add eslint disabled

- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/perm-template/components/render-action.vue
> feat: add semi

- frontend/.eslintrc.js
> feat: update .eslintrc

- saas/backend/common/error_codes.py
- saas/backend/component/constants.py
- saas/backend/component/engine.py
- saas/backend/component/esb.py
- saas/backend/component/http.py
- saas/backend/component/iam.py
- saas/backend/component/login.py
- saas/backend/component/resource_provider.py
- saas/backend/component/util.py
> Ft component http patch

- saas/backend/component/resource_provider.py
> feat(component/resource_provider): list_attr ignore {"id": "id"}

- frontend/src/views/group/components/render-instance-table.vue
> fix: fix 用户组添加权限无法选择资源实例

- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/group/create/index.vue
> fix: fix submit bugs

- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/group/create/index.vue
> Fe cartesian product

- saas/.gitignore
- saas/backend/biz/org_sync/department.py
- saas/config/default.py
- saas/resources/apigateway/definition.yaml
> fix(org sync): deparment sync wrong

- frontend/index.html
- frontend/src/views/group/detail/group-perm-new.vue
- frontend/src/views/set/components/render-super-manager.vue
- fix: 修复添加超级管理员实际无超级管理员权限的bug
> fix: 修复添加超级管理员实际无超级管理员权限的bug

- frontend/src/views/group/components/add-group-perm-sideslider.vue
> fix: 修复缺失跨页选中的权限模板

- saas/build/v3/bin/sync_apigateway.sh
> fix(apigw): sync resource update error

- saas/backend/biz/group.py
- 修复查询用户有权限的用户组列表对于相同用户组不同来源(直接或继承组织)只保留一个用户组的问题
- Fixes #
> fix(user group): miss same group with diff expired_at

- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
> fix: 修复提交loading时可以点击的bug

- frontend/src/views/resource-permiss/index.vue
> fix: add user id

- frontend/src/views/apply/components/perm-table.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/perm/custom-perm/custom-perm-table.vue
> feat: 样式优化

- frontend/src/views/system-access/index.vue
> add tocreate function

- frontend/src/views/perm-template/edit/difference.vue
> fix: fix vrmp system bug

- frontend/src/views/perm-apply/components/resource-instance-table.vue
- fix: 申请有关联权限，选择实例后，默认期限会变为不可更改
> fix: 申请有关联权限，选择实例后，默认期限会变为不可更改

- frontend/src/views/group/components/iam-add-member.vue
> fix: 隐藏搜索框

- saas/backend/api/authorization/serializers.py
- saas/backend/api/management/constants.py
- saas/backend/api/management/serializers.py
- saas/backend/api/management/urls.py
- saas/backend/api/management/views/__init__.py
- saas/backend/api/management/views/grade_manager.py
- saas/backend/api/management/views/group.py
- saas/backend/biz/role.py
- saas/backend/service/role.py
- 新增API - 查询分级管理员列表
- 更新API - 用户组授予与资源无关授权的API
- 新增API - 用户组回收权限API
- Fixes #
> feat(mgmt api): add and update api

- saas/backend/api/management/serializers.py
- saas/backend/api/management/views/grade_manager.py
- saas/backend/api/management/views/group.py
- saas/backend/apps/group/views.py
- saas/backend/apps/role/serializers.py
- saas/backend/apps/role/views/role.py
- saas/backend/biz/group.py
- saas/backend/biz/role.py
- saas/config/default.py
* 新增数据对象限制
- 每个系统可创建最多100个分级管理员
- 一个分级管理员可添加的成员个数：100
- 一个用户可加入的分级管理员个数：100
- 一个分级管理员可创建的用户组个数: 100
- Fixes #
> feat(object limit): perfect

- saas/backend/apps/mgmt/serializers.py
- Fixes #
api白名单添加增加无限制(\*)，即可以传递api=\*
> fix:API白名单增加无限制

- frontend/src/views/resource-permiss/index.vue
> fix: 修复资源权限管理查询bug

- frontend/src/views/grading-admin/components/render-instance-table.vue
- fix: modify related_resource_types
> fix: modify related_resource_types

- saas/backend/plugins/application_ticket/itsm/ticket_content.py
- saas/config/default.py
- 移除重复的配置
- 修复分级管理员申请单在ITSM显示问题
- Fixes #919
> Bugfix 1.7.10

- saas/backend/common/exception_handler.py
- saas/backend/common/middlewares.py
- saas/config/default.py
> Ft temporary policy

- saas/config/v2.py
- saas/config/v3.py
> feat(config): support set log level from env var

- saas/backend/metrics/__init__.py
> feat(metrics): support login component

- saas/backend/api/admin/views/group.py
- saas/backend/api/management/views/group.py
- saas/backend/common/pagination.py
- saas/backend/service/resource.py
- Open API 分页参数从limit/offset 调整为 page_size/page
- #967
> feat(open api): adjust page param from limit/offset to page_size/page

- saas/backend/common/pagination.py
> fix(page param): not be set

- release.md
- saas/resources/version_log/V1.7.12_2022-04-13_en.md
- saas/resources/version_log/V1.7.13_2022-04-19.md
- saas/resources/version_log/V1.7.13_2022-04-19_en.md
> docs(version log): v1.7.13

- saas/backend/api/admin/views/group.py
- saas/backend/api/management/views/grade_manager.py
- saas/backend/api/management/views/group.py
- saas/backend/common/pagination.py
- 新增的OpenAPI 分页参数默认为 page_siz/page
- Fixes #
> feat(open api): modify page params

- frontend/src/model/aggregation-policy.js
- frontend/src/model/grade-aggregation-policy.js
- frontend/src/model/group-aggregation-policy.js
- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/grading-admin/create/index.vue
- frontend/src/views/grading-admin/edit/index.vue
- frontend/src/views/group/add-perm/index.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/group/create/index.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/components/resource-instance-table.css
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- feat: add aggregateResource data
> feat: add aggregateResource data

- frontend/src/store/index.js
> feat: add router

- saas/backend/audit/models.py
> feat(performance optimization): cache audit table models

- frontend/src/views/grading-admin/edit/index.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
> fix: fix 聚合bug

- frontend/src/model/aggregation-policy.js
- frontend/src/model/grade-aggregation-policy.js
- frontend/src/model/group-aggregation-policy.js
- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/grading-admin/create/index.vue
- frontend/src/views/grading-admin/edit/index.vue
- frontend/src/views/group/add-perm/index.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/group/create/index.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
> feat: 聚合操作支持多个业务集

- saas/backend/api/management/serializers.py
- saas/backend/api/management/urls.py
- saas/backend/api/management/views/grade_manager.py
- saas/backend/apps/role/views/role.py
- saas/backend/biz/role.py
- saas/backend/service/role.py
- saas/backend/trans/open_management.py
- saas/backend/util/model.py
feat #933
- 新增管理类API - 更新分级管理员
- Fixes #
> feat(mgmt api): add api - update role

- saas/backend/apps/mgmt/constants.py
- saas/backend/apps/mgmt/filters.py
- saas/backend/apps/mgmt/serializers.py
- saas/backend/apps/mgmt/urls.py
- saas/backend/apps/mgmt/views/__init__.py
- saas/backend/apps/mgmt/views/long_task.py
- saas/backend/biz/group.py
- saas/backend/long_task/constants.py
- saas/backend/service/constants.py
- 增加长时任务展示列表【包括任务类型、任务状态、任务相关参数】
- 增加长时任务详情展示【包括子任务ID、子任务状态、子任务异常信息】
- 增加长时任务失败重试
- [Fixes #](https://github.com/TencentBlueKing/bk-iam-saas/issues/199)
> feat: show and retry long_task #issue199

- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/grading-admin/create/index.vue
- frontend/src/views/grading-admin/edit/index.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
> feat: 聚合操作逻辑修改

- frontend/src/model/aggregation-policy.js
- frontend/src/model/grade-aggregation-policy.js
- frontend/src/model/group-aggregation-policy.js
- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- feat: modify aggregation value
> feat: modify aggregation value

- frontend/src/model/aggregation-policy.js
- frontend/src/model/grade-aggregation-policy.js
- frontend/src/model/group-aggregation-policy.js
> feat: 修改符号

- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
> fix: 修改判断条件

- saas/backend/api/application/serializers.py
- saas/backend/api/authorization/serializers.py
- saas/backend/api/management/serializers.py
- saas/backend/apps/application/base_serializers.py
- saas/backend/apps/policy/serializers.py
- saas/backend/apps/resource/serializers.py
- saas/backend/apps/role/serializers.py
- saas/config/default.py
- saas/config/dev.py
- saas/config/v2.py
- saas/config/v3.py
> feat(limit): check the max length of resource id

- frontend/src/views/group/components/render-instance-table.vue
> fix: fix group bugs

- saas/config/ce.py
> fix: fix config ce

- saas/backend/api/authentication.py
> fix(backend/api/authentication.py): update esb jwt deocde

- saas/backend/common/cache.py
> fix(cache): resource get many error

- saas/backend/api/share/__init__.py
- saas/backend/api/share/permissions.py
- saas/backend/api/share/serializers.py
- saas/backend/api/share/urls.py
- saas/backend/api/share/views.py
- saas/backend/biz/system.py
- saas/config/default.py
- 新增Share API - 查询系统信息
- Fixes #
> feat(share api): audit system

- saas/backend/biz/role.py
> fix(limit): grade_manager_of_specified_systems_limit error

- saas/backend/api/share/permissions.py
> fix(share api): permission error

- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
> feat: 优化代码

- frontend/src/views/perm-apply/apply-custom-perm/index.vue
> feat: 新增按需申请

- frontend/src/views/perm-apply/components/resource-instance-table.css
- frontend/src/views/perm-apply/components/resource-instance-table.vue
> feat: 修改样式

- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/perm/index.vue
- frontend/src/views/perm/teporary-custom-perm/custom-perm-table.vue
- frontend/src/views/tempora-perm-apply/components/resource-instance-table.vue
> fix: fix default time

- saas/backend/common/local.py
- 修复local中request_id获取错误
- Fixes #
> fix(common/local): request_id get from local use the wrong key

- frontend/src/views/perm/index.vue
- fix: fix teporarySystemList length bug
> fix: fix teporarySystemList length bug

- frontend/src/model/policy.js
- frontend/src/views/tempora-perm-apply/components/resource-instance-table.vue
> fix: 修复临时权限未选业务集提交失败的bug

- frontend/src/model/policy.js
> feat: 修改update status

- saas/backend/api/authorization/mixins.py
- saas/backend/biz/group.py
- saas/backend/biz/role.py
- saas/backend/biz/utils.py
- saas/backend/common/error_codes.py
- saas/backend/common/exception_handler.py
- saas/poetry.lock
- saas/pyproject.toml
- saas/tests/biz/policy_tests.py
- 使用blue-krill的web.std_error重构 项目里的error_code
- Fixes #
> refactor(error_code): refactor use blue-krill.web.std_error

- frontend/src/components/choose-ip/grade.vue
- frontend/src/components/choose-ip/grade/index.vue
- frontend/src/components/choose-ip/index.vue
- frontend/src/components/choose-ip/sideslider.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
> feat: add ellipsisCopy

- saas/.pre-commit-config.yaml
- saas/backend/common/exception_handler.py
- saas/requirements.txt
- saas/requirements_dev.txt
> fix(poetry): not auto gen requirement

- frontend/src/components/common-action/index.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
> feat: 推荐权限标签不满足条件时要去掉选中

- saas/backend/api/management/views/group.py
- saas/backend/apps/group/views.py
- saas/backend/biz/group.py
> Ft limit grade manager

- frontend/src/views/grading-admin/components/render-instance-table.vue
- fix: edit rating-manager bug
> fix: edit rating-manager bug

- frontend/src/views/tempora-perm-apply/components/resource-instance-table.vue
> feat: 临时权限不需要操作状态

- frontend/src/views/tempora-perm-apply/components/resource-instance-table.vue
> feat: 自定义时间输入交互优化

- frontend/src/views/group/create/index.vue
- feat: add message ellipsisCopy
> feat: add message ellipsisCopy

- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/tempora-perm-apply/components/resource-instance-table.vue
> fix: 多个资源实例无法点击的bug

- frontend/src/views/tempora-perm-apply/apply-custom-perm/index.vue
> fix: 临时权限tab bugfix

- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/tempora-perm-apply/components/resource-instance-table.vue
> feat: 跨系统编辑无资源实例合并delete console

- frontend/src/views/perm-apply/apply-custom-perm/index.css
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- saas/resources/templates/group_expired_mail.html
- saas/resources/templates/user_expired_mail.html
> feat: 邮件模板文案修改

- frontend/src/views/grading-admin/components/add-action-sideslider.vue
- frontend/src/views/perm-template/components/render-content.vue
> feat: 用户组快捷操作修复

- saas/backend/api/admin/constants.py
- saas/backend/api/admin/serializers.py
- saas/backend/api/admin/urls.py
- saas/backend/api/admin/views/__init__.py
- saas/backend/api/admin/views/subject.py
- saas/backend/biz/subject.py
- saas/backend/component/iam.py
- saas/backend/service/subject.py
- 增加冻结/解冻/查询冻结用户列表接口
- Fixes #
> feat(api/admin): add freeze/unfreeze apis

- saas/backend/api/admin/views/subject.py
> feat(api/admin): user admin can't be freezed

- frontend/src/api/index.js
> feat: add show-login-modal

- frontend/src/components/header-nav/index.vue
- frontend/src/components/nav/index.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.css
> feat: modify css

- frontend/src/App.vue
- frontend/src/components/header-nav/index.css
- frontend/src/components/header/index.css
> Header nav

- saas/backend/component/iam.py
> feat(backend/api): change some urls to newest

- saas/backend/api/admin/views/subject.py
- saas/backend/audit/audit.py
- saas/backend/audit/constants.py
> Ft audit for user freeze

- frontend/src/components/header-nav/index.css
- frontend/src/components/header-nav/index.vue
- frontend/src/components/header/index.css
- frontend/src/main.js
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/tempora-perm-apply/components/resource-instance-table.vue
- saas/resources/templates/group_expired_mail.html
- saas/resources/templates/user_expired_mail.html
> fix: 无权限校验问题

- saas/backend/api/admin/views/subject.py
- saas/backend/api/management/views/user.py
- saas/backend/apps/group/filters.py
- saas/backend/apps/handover/validation.py
- saas/backend/apps/subject/views.py
- saas/backend/apps/user/tasks.py
- saas/backend/apps/user/views.py
- saas/backend/biz/group.py
- saas/backend/component/iam.py
- saas/backend/service/group.py
- subject_groups分页 
- Fixes #1155
> feat(iam/subject_groups): add paging for subject-groups

- frontend/package.json
- frontend/src/store/modules/perm.js
- frontend/src/store/modules/renewal.js
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/apply-join-user-group/index.vue
- frontend/src/views/perm/components/render-renewal-table.vue
- frontend/src/views/perm/group-perm/index.vue
- frontend/src/views/perm/index.vue
- frontend/src/views/perm/perm-renewal/index.vue
- frontend/src/views/tempora-perm-apply/apply-custom-perm/index.vue
- frontend/src/views/tempora-perm-apply/apply-join-user-group/index.vue
- frontend/src/views/transfer/group.vue
- frontend/src/views/user/components/group-perm.vue
- frontend/src/views/user/components/joined-user-group.vue
> feat: 分页数据变更

- saas/backend/api/admin/views/subject.py
- saas/backend/apps/subject/urls.py
- saas/backend/apps/subject/views.py
- saas/backend/apps/user/tasks.py
- saas/backend/apps/user/urls.py
- saas/backend/apps/user/views.py
- saas/backend/biz/group.py
- saas/backend/service/group.py
- list_subject_group 去掉 is_recursive 参数
- 增加 list user - departments - groups API
- Fixes #
> feat(user/group): remove recursive from list_subject_group

- frontend/src/components/header-nav/index.vue
> feat: 权限管理未切换tab也显示遮罩

- saas/backend/apps/user/tasks.py
- saas/backend/biz/policy.py
- saas/backend/common/lock.py
- saas/backend/service/template.py
> feat(rbac): group template lock

- saas/backend/api/management/views/group.py
> fix(mgmt api): delete group action slz wrong

- frontend/src/router/index.js
> fix: 修复初始化页面跳转bug

- saas/backend/api/management/v2/views/group.py
- saas/backend/api/management/v2/views/subject.py
> fix(rbac): v2 mgmt api perm

- saas/backend/api/management/v2/serializers.py
- saas/backend/api/management/v2/views/group.py
- saas/backend/api/management/v2/views/subject.py
> fix: fix mgmt v2 api

- saas/backend/api/management/v1/views/group.py
- saas/backend/api/management/v2/views/group.py
- saas/backend/biz/group.py
> fix: fix open api group grant policy api check

- saas/backend/api/management/v1/views/application.py
- saas/backend/api/management/v2/views/application.py
- saas/backend/apps/application/views.py
- saas/backend/apps/group/serializers.py
- saas/backend/biz/group.py
- saas/config/default.py
> feat: remove subject group limit check

- saas/tests/service/policy/backend_tests.py
- saas/tests/service/policy/common_tests.py
> test: add service policy tests

- saas/backend/tracing/apps.py
- saas/backend/tracing/instrumentor.py
- saas/backend/tracing/otel.py
- saas/backend/tracing/sentry.py
- saas/config/default.py
- update: otel 模块及配置更新
- Fixes #
> ft(otel): update the otel settings

- frontend/src/components/nav/index.vue
- frontend/src/router/index.js
- frontend/src/store/index.js
> fix: 多窗口页面切换问题权限问题-刷新问题

- saas/backend/api/management/mixins.py
> feat: update management api error message

- saas/resources/apigateway/bk_apigw_resources_bk-iam.yaml
- saas/resources/apigateway/docs/zh/management_grade_manager_groups.md.j2
- saas/resources/apigateway/docs/zh/management_grade_managers_list.md.j2
- saas/resources/apigateway/docs/zh/management_grade_managers_update.md.j2
- saas/resources/apigateway/docs/zh/management_group_members.md.j2
- saas/resources/apigateway/docs/zh/management_groups_policies_delete.md.j2
- saas/resources/apigateway/docs/zh/management_groups_policies_revoke_by_action.md.j2
- saas/resources/apigateway/docs/zh/v2_management_add_group_members.md.j2
- saas/resources/apigateway/docs/zh/v2_management_check_department_group_belong.md.j2
- saas/resources/apigateway/docs/zh/v2_management_check_user_group_belong.md.j2
- saas/resources/apigateway/docs/zh/v2_management_delete_group_members.md.j2
- saas/resources/apigateway/docs/zh/v2_management_grade_manager_create_groups.md.j2
- saas/resources/apigateway/docs/zh/v2_management_grade_manager_delete_group.md.j2
- saas/resources/apigateway/docs/zh/v2_management_grade_manager_update_group.md.j2
- saas/resources/apigateway/docs/zh/v2_management_group_members.md.j2
- saas/resources/apigateway/docs/zh/v2_management_groups_applications.md.j2
- saas/resources/apigateway/docs/zh/v2_management_groups_policies_action_list.md.j2
- saas/resources/apigateway/docs/zh/v2_management_groups_policies_grant.md.j2
- saas/resources/apigateway/docs/zh/v2_management_groups_policies_revoke.md.j2
- saas/resources/apigateway/docs/zh/v2_management_groups_policies_revoke_by_action.md.j2
- saas/resources/apigateway/docs/zh/v2_management_update_group_members_expired_at.md.j2
- saas/resources/apigateway/docs/zh/v2_policy_auth.md.j2
- saas/resources/apigateway/docs/zh/v2_policy_query.md.j2
> docs: add v2 api docs

- saas/resources/apigateway/docs/zh/_api_v1_model_actions.md.j2
- saas/resources/apigateway/docs/zh/system_add_actions.md.j2
- saas/resources/apigateway/docs/zh/system_get_policy.md.j2
- saas/resources/apigateway/docs/zh/system_policies.md.j2
- saas/resources/apigateway/docs/zh/system_policies_subjects.md.j2
> docs: update rbac api docs

- frontend/src/components/header-nav/index.vue
- frontend/src/store/index.js
> fix: 权限管理代码更改

- saas/backend/apps/user/tasks.py
> fix: fix user permission api

- saas/resources/app.yml
> docs: update app.yml

- saas/backend/api/authentication.py
> fix: fix esb jwt app verified

- saas/backend/apps/policy/views.py
> fix: update related policy

- saas/backend/api/management/v1/views/application.py
- saas/backend/api/management/v2/views/application.py
- saas/backend/apps/application/views.py
- saas/backend/biz/group.py
- saas/backend/component/iam.py
- saas/backend/service/group.py
> feat: add group application quota check

- saas/backend/api/management/v1/serializers.py
> fix: update

- saas/backend/common/exception_handler.py
- saas/backend/common/pagination.py
- saas/config/default.py
> feat: update web api default pagination

- saas/backend/apps/group/views.py
- saas/backend/apps/policy/views.py
- saas/backend/apps/subject/views.py
- saas/backend/apps/template/views.py
- saas/backend/apps/temporary_policy/views.py
- saas/backend/apps/user/views.py
- saas/backend/component/iam.py
- saas/config/ce.py
- saas/config/v2.py
> feat: remove permission logger

- saas/backend/apps/role/constants.py
- saas/backend/apps/role/tasks.py
- saas/backend/biz/role.py
- saas/backend/common/exception_handler.py
- saas/backend/common/pagination.py
- saas/backend/component/sops.py
- saas/config/default.py
> refactor: udpate policy_expired_at to expired_at

- saas/backend/apps/role/tasks.py
> Ft init manager

- saas/backend/api/management/v2/views/group.py
- saas/backend/apps/group/views.py
- saas/backend/apps/role/views/role.py
- saas/backend/biz/application.py
- saas/backend/biz/group.py
- saas/backend/component/iam.py
- saas/backend/service/group.py
> feat: update policy_expired_at to expired_at

- docs/quick_start/develop.md
- saas/Makefile
> feat: update Makefile

- saas/backend/apps/role/tasks.py
- saas/backend/biz/system.py
- saas/backend/component/iam.py
- saas/backend/service/system.py
> feat: init system manager query system manger config

- frontend/src/views/grading-admin/edit/index.vue
> fix: fix font size

- saas/backend/apps/role/tasks.py
- saas/backend/component/iam.py
> fix: update get_system_managers url

- saas/backend/apps/role/tasks.py
> feat: update init grade manager

- saas/backend/apps/role/tasks.py
> fix: update init grade manager (#1463)

- saas/backend/apps/role/tasks.py
> Ft fix url

- saas/backend/apps/group/views.py
- saas/backend/apps/policy/views.py
- saas/backend/apps/subject/views.py
- saas/backend/apps/template/views.py
- saas/backend/apps/temporary_policy/views.py
- saas/backend/apps/user/views.py
- saas/backend/component/iam.py
- saas/config/ce.py
- saas/config/v2.py
Reverts TencentBlueKing/bk-iam-saas#1437
> Revert "feat: remove permission logger"

- saas/backend/biz/application.py
> fix: fix policy renew use id

- saas/backend/biz/application.py
> feat: check user exists before application approved

- saas/backend/api/management/v1/serializers.py
- saas/backend/api/management/v2/serializers.py
> fix: bugfix check managment auth api action repeat

- frontend/src/store/modules/renewal.js
- frontend/src/views/perm/components/render-renewal-table.vue
- frontend/src/views/perm/perm-renewal/index.vue
- frontend/src/views/user/components/group-perm.vue
> fix: 用户组分页功能

- saas/backend/apps/role/tasks.py
- saas/backend/biz/role.py
- saas/backend/common/exception_handler.py
- saas/backend/common/time.py
> fix: fix expired display

- frontend/src/views/grading-admin/components/add-action-sideslider.vue
- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/group/components/add-action-sideslider.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/perm-template/components/render-content.vue
> fix: 修改单据问题

- frontend/src/views/group/clone/index.vue
- frontend/src/views/group/components/render-instance-table.vue
> feat: 修改聚合操作

- frontend/src/views/group/clone/index.vue
- frontend/src/views/group/components/render-instance-table.vue
* feat: 修改聚合操作
* feat: 修改聚合操作粘贴的bug
- xxxx
- Fixes #
> feat: 修改聚合操作 (#1493)

- frontend/src/views/perm/index.vue
> feat: 禁用tip

- frontend/src/views/group/clone/index.vue
- frontend/src/views/group/components/render-instance-table.vue
> feat: 打开添加组权限

- frontend/index.html
> feat: 国际化处理

- saas/backend/apps/role/tasks.py
> bugfix: role init task with resource name

- saas/backend/apps/role/tasks.py
> bugfix: init grade manager

- saas/backend/apps/role/tasks.py
- saas/backend/apps/user/tasks.py
- saas/backend/biz/group.py
- saas/backend/component/iam.py
- saas/backend/service/group.py
> feat: split expire remind task

- saas/backend/apps/role/tasks.py
- saas/backend/apps/user/tasks.py
> fix: fix remind mail task

- saas/backend/api/management/v1/serializers.py
- saas/backend/api/management/v2/serializers.py
- saas/backend/biz/group.py
- saas/backend/service/group.py
> fix: management api create group readonly update

- saas/resources/apigateway/docs/zh/management_grade_managers.md.j2
- saas/resources/apigateway/docs/zh/v2_management_check_department_group_belong.md.j2
> docs: update v2 api docs

- saas/backend/trans/open_management.py
> fix: fix management api group grant expired at permanent

- saas/backend/apps/role/views/role.py
> bugfix: system manager member update audit

- frontend/src/components/choose-ip/sideslider.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/group/create/index.vue
> fix: 修复在批量操作中可以选择没有权限的实例资源

- frontend/src/views/grading-admin/components/render-instance-table.vue
> fix: 用户管理权限显示为paas平台

- frontend/src/views/group/components/render-instance-table.vue
> fix: 修改业务集批量粘贴问题

- saas/resources/apigateway/docs/zh/_api_v2_status_code.md.j2
- saas/resources/apigateway/docs/zh/v2_management_add_group_members.md.j2
- saas/resources/apigateway/docs/zh/v2_management_check_department_group_belong.md.j2
- saas/resources/apigateway/docs/zh/v2_management_check_user_group_belong.md.j2
- saas/resources/apigateway/docs/zh/v2_management_delete_group_members.md.j2
- saas/resources/apigateway/docs/zh/v2_management_grade_manager_create_groups.md.j2
- saas/resources/apigateway/docs/zh/v2_management_grade_manager_delete_group.md.j2
- saas/resources/apigateway/docs/zh/v2_management_grade_manager_update_group.md.j2
- saas/resources/apigateway/docs/zh/v2_management_group_members.md.j2
- saas/resources/apigateway/docs/zh/v2_management_groups_applications.md.j2
- saas/resources/apigateway/docs/zh/v2_management_groups_policies_action_list.md.j2
- saas/resources/apigateway/docs/zh/v2_management_groups_policies_grant.md.j2
- saas/resources/apigateway/docs/zh/v2_management_groups_policies_revoke.md.j2
- saas/resources/apigateway/docs/zh/v2_management_groups_policies_revoke_by_action.md.j2
- saas/resources/apigateway/docs/zh/v2_management_update_group_members_expired_at.md.j2
- saas/resources/apigateway/docs/zh/v2_policy_auth.md.j2
- saas/resources/apigateway/docs/zh/v2_policy_query.md.j2
> docs: update v2 api status code

- saas/backend/biz/role.py
> fix: fix _get_role_related_object_ids

- saas/backend/apps/template/migrations/0014_auto_20221102_1655.py
> fix: update (#1593)

- saas/backend/apps/role/views/role.py
> fix: update role members

- saas/backend/apps/action/serializers.py
- saas/backend/apps/action/views/action.py
- saas/backend/apps/role/views/role.py
- saas/backend/apps/system/serializers.py
- saas/backend/apps/system/views.py
- saas/backend/biz/role.py
> Ft subset manager

- frontend/src/components/choose-ip/grade.vue
- frontend/src/components/choose-ip/grade/index.vue
- frontend/src/components/choose-ip/index.vue
fix:修复chooseip拓扑组件点击查看更多漏缺搜索关键字
> fix:修复chooseip拓扑组件点击查看更多漏缺搜索关键字

- saas/backend/service/role.py
> fix: update sync_subset_manager_members

- saas/backend/biz/role.py
> fix: update query_grade_manager

- frontend/src/common/router-handle.js
- frontend/src/components/iam-edit/input.vue
- frontend/src/store/modules/userGroup.js
- frontend/src/views/group/components/distribute-to-dialog.vue
- frontend/src/views/group/index.vue
- frontend/src/views/manage-spaces/secondary-manage-space/create/index.vue
fix: 点击个人工作台会显示一级管理空间路由
fix:  新建二级管理空间成功后会跳转到一级管理空间
feature: 修改select组件，对接单个分配二级管理空间
> feature: 修改select组件，对接单个分配二级管理空间

- frontend/src/components/nav/index.vue
- frontend/src/router/ce.js
- frontend/src/router/ee.js
- frontend/src/router/ieod.js
- frontend/src/router/index.js
- frontend/src/views/group/components/distribute-to-dialog.vue
- frontend/src/views/my-manage-space/components/iam-edit/input.vue
- frontend/src/views/my-manage-space/components/iam-edit/member-selector.vue
- frontend/src/views/my-manage-space/detail/index.vue
- frontend/src/views/my-manage-space/index.vue
> feat: 我的空间管理完成

- frontend/src/store/modules/userGroup.js
- frontend/src/views/my-manage-space/components/iam-edit/member-selector.vue
- frontend/src/views/my-manage-space/index.vue
> fix: 我的管理空间tag标签对齐

- frontend/src/views/group/components/distribute-to-dialog.vue
- frontend/src/views/group/index.vue
fix:分配dialog回显已有的二级管理空间
fix: 过滤掉非二级管理空间的人员
> fix:分配dialog回显已有的二级管理空间

- saas/backend/apps/group/views.py
> fix: update group transfer api

- frontend/src/components/nav/index.vue
- frontend/src/views/my-manage-space/index.vue
> feat: 添加克隆

- frontend/src/common/router-handle.js
- frontend/src/components/header-nav/index.vue
- frontend/src/components/header/index.vue
- frontend/src/components/nav/index.vue
- frontend/src/router/ce.js
- frontend/src/router/ee.js
- frontend/src/router/ieod.js
- frontend/src/views/my-manage-space/detail/index.vue
> fix: 修复跳转时不刷新页面的bug

- saas/backend/biz/role.py
> fix: update role relation checker

- saas/backend/apps/role/serializers.py
- saas/backend/apps/role/views/role.py
- saas/backend/service/role.py
> feat: subset manager add sync perm

- saas/backend/biz/group.py
> fix: fix create_sync_perm_group_by_role

- saas/backend/apps/role/views/role.py
> fix: subset manager list add filter

- frontend/src/model/group-policy.js
- frontend/src/router/index.js
> feat: 用户组详情

- saas/resources/apigateway/bk_apigw_resources_bk-iam.yaml
- saas/resources/apigateway/docs/zh/v2_management_application_approve.md.j2
- saas/resources/apigateway/docs/zh/v2_management_grade_manager_applications.md.j2
- saas/resources/apigateway/docs/zh/v2_management_grade_manager_create_subset_manager.md.j2
- saas/resources/apigateway/docs/zh/v2_management_grade_manager_list_groups.md.j2
- saas/resources/apigateway/docs/zh/v2_management_subset_manager_create_groups.md.j2
- saas/resources/apigateway/docs/zh/v2_management_subset_manager_list_groups.md.j2
- saas/resources/apigateway/docs/zh/v2_management_update_grade_manager_application.md.j2
> docs: add new v2 api

- saas/resources/apigateway/docs/zh/v2_management_check_department_group_belong.md.j2
- saas/resources/apigateway/docs/zh/v2_management_check_user_group_belong.md.j2
> docs: update v2 belong api response

- saas/resources/apigateway/bk_apigw_resources_bk-iam.yaml
- saas/resources/apigateway/docs/zh/v2_management_application_cancel.md.j2
> docs: add v2 management api application cancel

- saas/resources/apigateway/bk_apigw_resources_bk-iam.yaml
- saas/resources/apigateway/docs/zh/v2_management_grade_manager_create.md.j2
- saas/resources/apigateway/docs/zh/v2_management_update_grade_manager.md.j2
> docs: add v2 grade manager api

- frontend/src/common/util.js
- frontend/src/router/index.js
- frontend/src/store/index.js
- frontend/src/views/apply/index.vue
- frontend/src/views/perm/index.vue
- frontend/src/views/perm/perm-renewal/index.vue
- frontend/src/views/transfer/group.vue
> feat: 新增配置项获取接口

- frontend/src/components/choose-ip/grade/index.vue
> fix: 修复克隆用户组数据没有在第一页的bug

- saas/backend/apps/policy/views.py
- saas/backend/biz/action.py
- saas/backend/service/resource.py
> fix: some optimization

- saas/resources/apigateway/docs/zh/v2_management_grade_manager_detail.md.j2
> docs: update

- saas/backend/api/management/v2/views/application.py
> fix: update application cancel

- saas/backend/api/management/v1/filters.py
- saas/backend/api/management/v1/views/grade_manager.py
- saas/backend/biz/role.py
- saas/backend/service/role.py
> feat: update v1 grade manger list api

- frontend/src/views/group/detail/group-perm-new.vue
- frontend/src/views/perm/perm-renewal/index.vue
> feat: add canedit 字段

- saas/resources/apigateway/docs/zh/_api_v1_model_system_config.md.j2
- saas/resources/apigateway/docs/zh/system_add_configs.md.j2
- saas/resources/apigateway/docs/zh/system_update_configs.md.j2
> fix: fix docs

- frontend/src/components/choose-ip/grade/index.vue
- frontend/src/views/group/clone/index.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/group/create/index.vue
> fix: 修复克隆选择实例请求全量数据的问题

- frontend/src/components/nav/index.vue
- frontend/src/views/my-manage-space/index.vue
> fix:修复F5强制刷新后被选中的子集空间icon未变

- saas/backend/apps/group/filters.py
- saas/backend/apps/group/views.py
- saas/backend/apps/resource/serializers.py
- saas/backend/apps/resource/views.py
- saas/backend/apps/system/urls.py
- saas/backend/biz/resource_type.py
- saas/backend/component/iam.py
- saas/backend/service/group.py
- saas/backend/service/resource_type.py
> feat: add system resource type api

- saas/backend/apps/resource/serializers.py
> fix: update sytem resource type slz

- saas/backend/api/management/v1/views/grade_manager.py
- saas/backend/api/management/v1/views/group.py
- saas/backend/api/management/v2/views/application.py
- saas/backend/api/management/v2/views/grade_manager.py
- saas/backend/api/management/v2/views/group.py
- saas/backend/apps/application/views.py
- saas/backend/apps/group/views.py
- saas/backend/apps/role/views/role.py
- saas/backend/apps/template/views.py
- saas/backend/common/lock.py
> feat: add role group template create name check lock

- saas/backend/biz/application.py
> fix: update handle_application_result

- saas/backend/service/utils/translate.py
- saas/tests/service/translate_tests.py
> feat: add translate path valid

- saas/backend/api/management/mixins.py
- saas/backend/api/management/models.py
- saas/backend/biz/system.py
> feat: update management api permission cache

- saas/backend/iam/providers.py
> feat: update iam resource provider

- saas/backend/api/urls_v2.py
> fix: fix v2 management api url

- frontend/src/views/group/create/index.vue
- frontend/src/views/my-manage-space/add-member-boundary/index.vue
> feat: 修改postmessage格式

- frontend/src/views/my-manage-space/add-member-boundary/index.vue
> feat: 添加弹窗cancel

- saas/backend/audit/tasks.py
> fix: update audit log task

- saas/backend/service/models/application.py
> fix: update v2 management application api

- saas/backend/service/policy/query.py
> fix: update service policy get_policy_system_by_id

- saas/backend/service/policy/query.py
> fix: fix service policy query get_policy_system_by_id

- saas/backend/api/management/v2/views/group.py
> fix: fix v2 management api group filter

- saas/config/ce.py
- saas/config/v2.py
> fix: update django redis sentinel

- saas/backend/common/management/__init__.py
- saas/backend/common/management/commands/__init__.py
- saas/backend/common/management/commands/celery.py
- saas/config/default.py
> feat: add celery command adapter

- saas/backend/apps/action/tasks.py
- saas/backend/apps/application/tasks.py
- saas/backend/apps/group/tasks.py
- saas/backend/apps/handover/tasks.py
- saas/backend/apps/organization/tasks.py
- saas/backend/apps/policy/tasks.py
- saas/backend/apps/role/tasks.py
- saas/backend/apps/temporary_policy/tasks.py
- saas/backend/apps/user/tasks.py
- saas/backend/audit/tasks.py
- saas/backend/common/management/__init__.py
- saas/backend/common/management/commands/__init__.py
- saas/backend/common/management/commands/celery.py
- saas/backend/long_task/tasks.py
- saas/config/default.py
> Ft requirements

- saas/backend/api/management/v2/filters.py
> feat: v2 management api group list add description filter

- saas/backend/api/management/v2/filters.py
> feat: v2 management api group list add description filter (#1727)

- saas/backend/account/backends.py
- saas/backend/api/application/serializers.py
- saas/backend/api/application/urls.py
- saas/backend/api/application/views.py
- saas/backend/trans/open_application.py
> feat: add v1 application grant policies api

- saas/resources/apigateway/bk_apigw_resources_bk-iam.yaml
- saas/resources/apigateway/docs/zh/application_grant_policy.md.j2
- saas/resources/apigateway/docs/zh/v2_management_grade_manager_list_groups.md.j2
> docs: add application grant policy api

- saas/backend/common/error_codes.py
- saas/backend/common/exception_handler.py
> fix: fix UnsupportedMediaType exception

- frontend/src/views/manage-spaces/secondary-manage-space/components/render-instance-table.vue
- frontend/src/views/manage-spaces/secondary-manage-space/create/index.vue
- frontend/src/views/set/components/render-super-manager.vue
- frontend/src/views/set/components/render-system-manager.vue
fix: 成员列表多个成员显示问题
fix: 超级管理员和系统管理员限制表格高度
> fix: 成员列表多个成员显示问题

- frontend/src/router/ce.js
- frontend/src/router/ee.js
> fix:修复漏缺的其他环境的注册路由

- saas/backend/api/management/constants.py
- saas/backend/api/management/v2/urls.py
- saas/backend/api/management/v2/views/grade_manager.py
- saas/backend/api/management/v2/views/subset_manager.py
- saas/backend/apps/role/audit.py
- saas/backend/audit/constants.py
- saas/backend/biz/helper.py
> feat: add delete grade manger/subset manager api

- frontend/src/views/apply/components/basic-info.vue
> feature: 修改我的申请详情参数

- saas/backend/service/policy/operation.py
> fix: fix abac policy delete by id

- frontend/src/components/system-log/index.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm/group-perm-renewal/index.vue
fix: 修复申请自定义权限->用户组续期时间未过期，提示让用户去续期
> fix: 修复申请自定义权限->用户组续期时间未过期，提示让用户去续期

- saas/backend/apps/role/tasks.py
- saas/backend/healthz/views.py
> feat: update role init task

- frontend/src/views/perm-apply/apply-custom-perm/index.vue
> fix: 申请自定义权限->选择权限获得者提供默认值

- saas/backend/api/management/v1/views/application.py
- saas/backend/api/management/v2/views/application.py
- saas/backend/apps/application/views.py
- saas/backend/biz/application.py
- saas/backend/trans/application.py
- saas/backend/trans/open_application.py
- saas/bin/sync_apigateway.sh
> fix: fix group policy application applicants

- frontend/src/App.vue
- frontend/src/components/header/index.css
- frontend/src/store/index.js
- frontend/src/views/group/clone/index.vue
- frontend/src/views/group/common/render-perm-item-new.vue
- frontend/src/views/group/create/index.vue
- frontend/src/views/group/detail/group-detail.vue
- frontend/src/views/group/detail/group-perm-new.vue
- frontend/src/views/group/index.vue
- frontend/src/views/manage-spaces/secondary-manage-space/create/index.vue
- frontend/src/views/my-manage-space/add-member-boundary/index.vue
- frontend/src/views/perm-apply/apply-join-user-group/index.vue
- frontend/src/views/perm-template/components/render-group-perm-sideslider.vue
- frontend/src/views/perm-template/index.vue
- frontend/src/views/tempora-perm-apply/apply-join-user-group/index.vue
feature: 添加组权限时，注释掉新增模板
feature: 查看组详情页面，去掉组名称、组描述编辑
feature: 查看组权限， 过滤掉自定义权限申请的内容
feature: 修改系统主体高度问题，外部内嵌页面不计算高度值
feature: 修改蓝盾iframe嵌套设置项目最大可授权范围页面导致的样式问题
feature: 修改蓝盾iframe嵌套设置项目最大可授权范围页面父子组件数据通信数据结构
> feature:提交2-10的体验优化和蓝盾内嵌页面的一些需求

- saas/backend/api/management/v2/urls.py
> fix: fix management v2 api group renew url

- saas/backend/api/management/v2/serializers.py
- saas/backend/api/management/v2/views/application.py
- saas/resources/apigateway/docs/zh/v2_management_groups_renew_applications.md.j2
> fix: fix management v2 group renew api

- frontend/src/store/index.js
- frontend/src/views/apply/components/apply-create-rate-manager-detail.vue
- frontend/src/views/apply/components/left.vue
- frontend/src/views/apply/index.vue
- frontend/src/views/my-manage-space/add-member-boundary/index.vue
feature: 支持我的申请内嵌页面，可以通过传id参数自动选中当前列表数据，展示对应的详情页
> feature: 支持我的申请内嵌页面，可以通过传id参数自动选中当前列表数据，展示对应的详情页

- frontend/src/App.vue
- frontend/src/components/smart-action/index.vue
> fix:更改主入口文件设置的最小宽度值和修改底部按钮内边距

- saas/config/default.py
> feat: add temporary policy switch

- saas/backend/apps/role/tasks.py
> fix: fix role init

- frontend/src/views/group/add-perm/index.vue
- frontend/src/views/group/components/iam-add-member.vue
- frontend/src/views/group/components/member-table.vue
- frontend/src/views/group/detail/group-perm-new.vue
feature: 单独处理内嵌页面组权限->添加权限的跳转逻辑
feature: 单独处理内嵌页面用户组成员删除功能的传参
> feature: 单独处理内嵌页面组权限->添加权限的跳转逻辑

- saas/backend/api/management/v2/views/grade_manager.py
- saas/backend/biz/application.py
- saas/backend/biz/group.py
- saas/backend/service/group_saas_attribute.py
> Fix role init

- frontend/src/App.vue
- frontend/src/common/util.js
- frontend/src/components/header-nav/index.vue
- frontend/src/language/index.js
> feature: 封装单独的获取cookie方法

- saas/backend/biz/group.py
> fix: update role sync group name

- frontend/src/common/constants.js
- frontend/src/components/render-perm-boundary/index.vue
> fix: 组件标题改为配置化枚举

- frontend/src/components/header/index.vue
> fix: 修复文档跳转

- frontend/src/components/infinite-tree/index.vue
- frontend/src/views/group/components/add-action-sideslider.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/add-action-sideslider.vue
feature: 优化二级管理选择资源实例逻辑，防止字段缺失问题
> feature: 优化二级管理选择资源实例逻辑，防止字段缺失问题

- saas/backend/api/application/serializers.py
- saas/backend/trans/open_application.py
- saas/resources/apigateway/docs/en/authorization_batch_path.md.j2
- saas/resources/apigateway/docs/en/authorization_path.md.j2
- saas/resources/apigateway/docs/zh/application_grant_policy.md.j2
- saas/resources/apigateway/docs/zh/authorization_batch_path.md.j2
- saas/resources/apigateway/docs/zh/authorization_path.md.j2
> fix: application grant policies api add expired_at

- saas/backend/apps/group/serializers.py
- saas/backend/apps/group/urls.py
- saas/backend/apps/group/views.py
- saas/backend/apps/role/views/permission_audit.py
- saas/backend/biz/permission_audit.py
> feat: add group search api

- saas/backend/api/bkci/filters.py
> fix: ci migrate api add version filter

- frontend/src/views/perm-apply/apply-join-user-group/index.vue
> fix； 增加多字段搜索校验，去掉值为空的搜索字段

- frontend/commitlint.config.js
- frontend/mock/ajax/index.js
- frontend/mock/ajax/util.js
- frontend/postcss.config.js
- frontend/src/common/file-saver.js
> fix: 修复eslint相关缩进

- .github/workflows/python.yml
- saas/config/ce.py
- saas/config/default.py
- saas/resources/apigateway/definition.yaml
> feat: update config

- frontend/src/views/perm-apply/apply-join-user-group/index.vue
> fix:  修复固定宽度太宽导致小屏幕溢出问题

- frontend/index.html
- frontend/src/App.vue
- frontend/src/common/util.js
- frontend/src/components/header-nav/index.vue
- frontend/src/language/index.js
- frontend/src/router/index.js
- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/group/add-perm/index.vue
- frontend/src/views/group/clone/index.vue
- frontend/src/views/group/components/add-group-perm-sideslider.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/group/create/index.vue
- frontend/src/views/group/detail/group-perm-new.vue
- frontend/src/views/manage-spaces/components/render-instance-table.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/render-instance-table.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/perm-template/components/render-content.vue
- frontend/src/views/tempora-perm-apply/components/resource-instance-table.vue
> fix: 添加组权限单个资源实例粘贴报错问题

- frontend/src/views/perm/custom-perm/custom-perm-table.vue
> fix: 修复线上报错问题

- frontend/index.html
> feat: add bkdomain

- saas/backend/audit/routers.py
- saas/backend/service/action.py
> fix: fix audit db routers

- saas/backend/audit/routers.py
- saas/backend/biz/policy.py
- saas/backend/service/action.py
> Bugfix 1.10.7

- saas/backend/biz/application.py
- saas/backend/biz/policy.py
> fix: show hidden permission for group application

- frontend/src/views/group/components/member-table.vue
- frontend/src/views/perm/custom-perm/custom-perm-table.vue
fix: 用户组组织架构字段根据type区分full_name
> fix: 用户组组织架构字段根据type区分full_name

- saas/backend/apps/application/base_serializers.py
- saas/backend/trans/policy.py
> feat: aggregate_resource_types support any

- saas/backend/apps/role/serializers.py
- saas/config/default.py
> feat: add organization count switch

- frontend/src/views/group/components/member-table.vue
> feature: 用户组详情表格隐藏数量

- saas/backend/apps/role/views/role.py
- saas/backend/biz/role.py
- saas/backend/common/error_codes.py
> fix: fix super manger role list

- saas/backend/apps/role/views/role.py
> Bugfix role list

- frontend/src/App.vue
- frontend/src/api/index.js
- frontend/src/components/exception-empty/index.vue
- frontend/src/views/403.vue
> feature: 无限制页面改为全屏展示

- saas/backend/account/backends.py
> fix: fix login forbidden message

- saas/backend/account/backends.py
> Bugfix login

- saas/backend/apps/role/views/role.py
> fix: fix role partial_update

- saas/backend/apps/role/views/role.py
> Bugfix role partial update

- frontend/src/api/index.js
- frontend/src/main.js
* fix: 修复403无权限跳转问题
* fix: 优化403交互
* fix: 提价漏缺代码
- xxxx
- Fixes #
> fix: 修复403无权限跳转问题 (#2121)

- saas/backend/common/lock.py
> fix: lock free when timeout

- frontend/src/components/nav/index.vue
- frontend/src/views/user/index.vue
fix: 优化角色选择器搜索内容不在当前页，搜索后清空关键词
> fix: 优化角色选择器搜索内容不在当前页，搜索后清空关键词

- saas/backend/apps/user/serializers.py
> fix: fix user group role memberss

- saas/backend/api/bkci/tasks.py
> feat: update ci task

- frontend/src/views/perm-apply/apply-join-user-group/index.vue
> fix: 注释已选用户组需求代码，待提供新的产品方案

- frontend/src/views/group/components/member-table.vue
> fix: 调整复制成员字体大小

- saas/backend/apps/application/views.py
> fix: fix super manager update role application

- saas/backend/apps/group/serializers.py
- saas/backend/apps/user/urls.py
- saas/backend/apps/user/views.py
> feat: add user group search api

- frontend/src/views/apply/common/render-member-display.vue
- frontend/src/views/group/common/render-member-display.vue
- frontend/src/views/manage-spaces/secondary-manage-space/common/render-member-display.vue
> fix: 选择组织架构成员后需要展示内容隐藏count

- frontend/src/css/mixins/apply-join-group-search.css
- frontend/src/views/perm-apply/apply-join-user-group/index.vue
> fix: 修复频繁切换分页，checkbox未更换状态

- frontend/src/router/index.js
fix:  修复发送的邮件里用户组成员续期点击续期跳转过来的链接错误
> fix:  修复发送的邮件里用户组成员续期点击续期跳转过来的链接错误

- frontend/src/components/choose-ip/sideslider.vue
- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/manage-spaces/components/render-instance-table.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/render-instance-table.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/tempora-perm-apply/components/resource-instance-table.vue
fix: 非超管角色获取授权范围的资源是任意类型调用resouce接口
> fix: 非超管角色获取授权范围的资源是任意类型调用resouce接口

- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/group/detail/group-perm-new.vue
fix:  组权限—> 最后一个系统操作item增加margin, 不让全屏铺满
> fix:  组权限—> 最后一个系统操作item增加margin, 不让全屏铺满

- saas/backend/account/urls.py
- saas/backend/account/views.py
- saas/backend/apps/user/urls.py
- saas/backend/apps/user/views.py
- saas/backend/biz/role.py
> feat: add user department group search api

- saas/backend/biz/action.py
> fix: action list hidden

- frontend/src/views/grading-admin/components/add-action-sideslider.vue
- frontend/src/views/group/components/add-action-sideslider.vue
- frontend/src/views/group/components/iam-add-member.vue
- frontend/src/views/group/detail/group-perm-new.vue
- frontend/src/views/manage-spaces/components/add-action-side-slider.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/add-action-sideslider.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-template/components/render-content.vue
- frontend/src/views/perm/custom-perm/custom-perm-table.vue
- frontend/src/views/perm/teporary-custom-perm/custom-perm-table.vue
- frontend/src/views/tempora-perm-apply/apply-custom-perm/index.vue
> fix:  平台所有action支持参数控制隐藏/显示

- saas/backend/apps/resource/views.py
- saas/backend/biz/resource.py
- saas/backend/service/resource.py
> feat: instance search add ancestors filter

- frontend/src/views/perm-apply/apply-join-user-group/index.vue
> fix: 先按临时方案只提交勾选的数据

- frontend/src/views/group/index.vue
> fix: 修复判断只读字段取值错误

- saas/backend/biz/policy.py
- saas/tests/biz/policy_tests.py
> fix: fix resource name check with none

- frontend/src/store/modules/perm.js
- frontend/src/views/my-manage-space/components/iam-edit/textarea.vue
- frontend/src/views/perm/index.vue
> fix:  textareaw去掉点击变更状态

- frontend/src/views/perm/custom-perm/custom-perm-table.vue
- frontend/src/views/perm/custom-perm/index.vue
- frontend/src/views/perm/department-group-perm/index.vue
- frontend/src/views/perm/group-perm/index.vue
- frontend/src/views/perm/index.vue
> fix: 修改我的权限->自定义权限业务交互

- saas/backend/api/management/v2/views/subset_manager.py
- saas/backend/plugins/application_ticket/itsm/itsm.py
> fix: fix group application title length

- frontend/src/views/perm/index.vue
> fix: 去掉系统数组注释

- saas/backend/api/management/v2/serializers.py
- saas/backend/api/management/v2/views/application.py
- saas/backend/biz/application.py
- saas/backend/plugins/application_ticket/base.py
- saas/backend/plugins/application_ticket/itsm/itsm.py
- saas/backend/service/application.py
> feat: add ci group application custom content

- saas/backend/api/management/constants.py
- saas/backend/api/management/v2/filters.py
- saas/backend/api/management/v2/views/subset_manager.py
> feat: add v2 managment subset manager list api

- saas/backend/api/management/v2/views/group.py
> fix: fix v2 managment system manager create group api

- saas/backend/api/management/v2/urls.py
- saas/backend/api/management/v2/views/__init__.py
- saas/backend/api/management/v2/views/subset_manager.py
> fix: fix subset manager list api

- frontend/package.json
> fix: 还原组件库原始版本

- saas/backend/api/management/v2/serializers.py
- saas/backend/biz/application.py
> fix: update group application custom content

- saas/backend/api/management/v2/serializers.py
- saas/backend/biz/application.py
> fix: update group application custom content (#2250)

- saas/resources/apigateway/bk_apigw_resources_bk-iam.yaml
- saas/resources/apigateway/docs/en/v2_management_grade_manager_list_subset_manager.j2
- saas/resources/apigateway/docs/zh/v2_management_grade_manager_list_subset_manager.j2
> docs: add subset manger list api docs

- frontend/src/views/grading-admin/components/add-action-sideslider.vue
- frontend/src/views/group/detail/group-perm-new.vue
> fix: 修复只读和管理员用户组不可添加权限

- saas/backend/api/initialization/serializers.py
- saas/backend/api/initialization/views.py
- saas/backend/apps/role/tasks.py
- saas/backend/biz/org_sync/syncer.py
- saas/backend/component/usermgr.py
> feat: sync user with departments

- frontend/build/build-dll.js
- frontend/src/components/iam-resource-cascade-search/index.vue
- frontend/src/views/group/index.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm/department-group-perm/index.vue
- frontend/src/views/perm/group-perm/index.vue
- frontend/src/views/perm/index.vue
- frontend/src/views/tempora-perm-apply/apply-custom-perm/index.vue
- frontend/src/views/tempora-perm-apply/apply-join-user-group/index.vue
> fix: 修改dll的hash

- frontend/src/components/iam-resource-cascade-search/index.vue
> feature: 蓝盾页面单独出来选择系统后不能清空

- saas/backend/apps/user/views.py
- saas/backend/common/filters.py
> fix: update group hidden filter

- saas/backend/apps/user/views.py
- saas/backend/common/filters.py
> Fix group filter

- saas/backend/api/initialization/serializers.py
> fix: update user sync slz

- saas/backend/api/initialization/serializers.py
- saas/backend/biz/role.py
> Fix user sync

- saas/backend/apps/organization/serializers.py
> fix: update user list length

- frontend/src/views/perm/components/render-renewal-table.vue
> fix: 修复用户组权限续期续期—>管理员列展示问题

- frontend/src/views/group/components/iam-add-member.vue
- frontend/src/views/manage-spaces/secondary-manage-space/create/index.vue
> feature: 权限中心统一人员选择器组件

- frontend/build/webpack.base.conf.js
- frontend/src/views/sensitivity-level/components/iam-batch-transfer-slider.vue
> fix: 提交漏缺代码

- saas/backend/common/vue.py
- saas/config/default.py
> feat: add doc url prefix

- saas/backend/apps/role/models.py
- saas/bin/start_celery.sh
> Fix celery oom

- saas/backend/biz/application.py
> fix: join group not exists

- saas/backend/apps/approval/views.py
> fix: fix action process filter by sensitivity_level

- saas/backend/common/vue.py
- saas/config/default.py
> Fix doc url

- frontend/index.html
- frontend/src/views/sensitivity-level/components/iam-batch-transfer-slider.vue
- frontend/src/views/sensitivity-level/components/sensitivity-level-table.vue
- frontend/src/views/sensitivity-level/components/sensitivity-right-layout.vue
- frontend/src/views/sensitivity-level/components/sensitivity-systems.vue
feature: 全部等级筛选字段去掉senstivity_level
> feature: 全部等级筛选字段去掉senstivity_level

- frontend/src/views/sensitivity-level/components/sensitivity-level-table.vue
- frontend/src/views/sensitivity-level/components/sensitivity-right-layout.vue
> fix: 提交漏缺的敏感等级代码

- frontend/src/views/sensitivity-level/components/sensitivity-level-table.vue
- frontend/src/views/sensitivity-level/components/sensitivity-right-layout.vue
> feature: 提交搜索参数修改

- frontend/src/views/group/components/member-table.vue
- frontend/src/views/my-manage-space/add-member-boundary/index.vue
- frontend/src/views/sensitivity-level/components/sensitivity-level-table.vue
- frontend/src/views/sensitivity-level/components/sensitivity-right-layout.vue
- frontend/src/views/sensitivity-level/components/sensitivity-systems.vue
- frontend/src/views/sensitivity-level/index.vue
> fix: 循环多个异步接口同步执行改为异步执行

- saas/backend/apps/approval/views.py
- saas/backend/biz/action.py
> fix: fix approval action list cache

- saas/backend/apps/approval/views.py
- saas/backend/biz/action.py
- saas/backend/service/action.py
> Fix action list

- frontend/src/store/index.js
- frontend/src/views/perm/group-perm/index.vue
- frontend/src/views/perm/index.vue
> fix: 我的权限退出后缓存条数（蓝盾需求）

- frontend/src/store/index.js
> feature: 开放敏感等级菜单到线上测试

- saas/backend/component/esb.py
> fix: update esb auth

- frontend/src/views/group/components/iam-add-member.vue
- frontend/src/views/my-manage-space/add-member-boundary/index.vue
> fix: 修复提示报错未清空问题

- saas/backend/apps/subject/urls.py
- saas/backend/apps/subject/views.py
- saas/backend/apps/user/views.py
> fix: fix subject policy search

- saas/backend/apps/subject/urls.py
- saas/backend/apps/subject/views.py
- saas/backend/apps/user/views.py
> Ft subject policy search

- saas/backend/apps/subject/serializers.py
- saas/backend/biz/group.py
> fix: user group slz add user count and department count

- saas/backend/biz/application_process.py
> fix: fix action sensitivity_level

- frontend/src/views/grading-admin/components/add-action-sideslider.vue
> fix: 管理空间去掉后台标识隐藏操作处理

- saas/backend/biz/application.py
- saas/backend/biz/application_process.py
- saas/backend/service/constants.py
- saas/backend/service/models/approval.py
> feat: add instance approver node support

- saas/backend/service/constants.py
> fix: update sensitivity level

- saas/backend/service/constants.py
> fix: update iam process node constants

- frontend/src/components/dialog-infinite-list/index.vue
- frontend/src/components/header/index.css
- frontend/src/components/header/index.vue
- frontend/src/views/group/components/iam-add-member.vue
- frontend/src/views/my-manage-space/add-member-boundary/index.vue
- frontend/src/views/my-manage-space/index.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/apply-join-user-group/index.vue
- frontend/src/views/perm/index.vue
feature: 处理i人员选择器组件在iam系统和蓝盾系统中不需要校验授权范围的页面
> feature: 处理i人员选择器组件在iam系统和蓝盾系统中不需要校验授权范围的页面

- saas/backend/service/constants.py
> fix: update instace paste

- frontend/src/model/grade-aggregation-policy.js
- frontend/src/model/group-aggregation-policy.js
- frontend/src/views/my-manage-space/add-member-boundary/index.vue
> fix: 去掉注释超过120字符限制代码

- frontend/src/common/constants.js
- frontend/src/components/render-renewal-dialog/index.vue
> fix: 模板名称列不能隐藏

- saas/config/default.py
> feat: cacnel role group expired remind

- saas/config/default.py
> feat: cancel role group expire remind

- saas/bin/start.sh
- saas/gunicorn_hooks.py
> feat: add gunicorn worker exit hook to clean metrics file

- saas/backend/common/time.py
> fix: fix seconds_to_display_str

- saas/backend/apps/user/tasks.py
> feat: don't remind expired policy or groups

- saas/backend/service/models/application.py
> fix: update group application fix sensitivity level

- saas/backend/service/models/application.py
> fix: update group application fix sensitivity level (#2438)

- frontend/src/components/iam-edit/textarea.vue
fix: 修复编辑textarea组件点击任意占位符触发失焦问题
> fix: 修复编辑textarea组件点击任意占位符触发失焦问题

- saas/backend/api/management/v2/views/group.py
- saas/backend/long_task/tasks.py
> fix: update grade manager group list api filter

- saas/resources/bkpkg-bkiam_saas.yaml
> feat: add bkpkag yaml file

- frontend/src/components/choose-ip/topology-manual-input.vue
> feature: 提交漏缺代码

- frontend/src/views/my-manage-space/add-member-boundary/index.vue
fix: 修复蓝盾内嵌页面最大授权范围选择组织后无法选择用户
> fix: 修复蓝盾内嵌页面最大授权范围选择组织后无法选择用户

- frontend/src/views/group/add-perm/index.vue
- frontend/src/views/group/clone/index.vue
- frontend/src/views/group/components/render-template-detail-sideslider.vue
- frontend/src/views/group/create/index.vue
fix: 用户组先添加操作和权限模板后，再取消操作或者对权限模板数量进行删减后不显示
> fix: 用户组先添加操作和权限模板后，再取消操作或者对权限模板数量进行删减后不显示

- saas/config/default.py
> feat: update manager member max count

- frontend/src/components/choose-ip/topology-tree.vue
- frontend/src/components/choose-ip/view/index.vue
- frontend/src/views/grading-admin/components/render-resource.vue
- frontend/src/views/group/components/render-resource.vue
- frontend/src/views/manage-spaces/components/render-resource.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/render-resource.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/components/render-resource.vue
- frontend/src/views/perm-template/components/render-resource.vue
- frontend/src/views/resource-permiss/components/render-resource.vue
- frontend/src/views/tempora-perm-apply/components/render-resource.vue
feature: 处理三层及以上拓扑数据与右侧便全选、多选联动
> feature: 处理三层及以上拓扑数据与右侧便全选、多选联动

- frontend/src/components/choose-ip/topology-tree.vue
fix: 修复多层拓扑数据第一次选中的时候无法快捷清空选中
fix: 多层拓扑重复切换点击，disabled或者checked状态不同步问题
> fix: 多层拓扑重复切换点击，disabled或者checked状态不同步问题

- saas/backend/biz/application.py
- saas/backend/plugins/application_ticket/itsm/itsm.py
- saas/backend/plugins/application_ticket/itsm/ticket_content.py
- saas/backend/plugins/application_ticket/itsm/ticket_content_tpl.py
- saas/backend/service/models/application.py
> feat: enhancement of ITSM Ticket Content Display

- saas/backend/plugins/application_ticket/itsm/itsm.py
> feat: add default itsm tag

- saas/config/default.py
- saas/poetry.lock
- saas/pyproject.toml
- saas/requirements.txt
- saas/requirements_dev.txt
- saas/urls.py
> Ft bk notice

- saas/backend/biz/application_process.py
> fix: update approval merge system manager

- saas/backend/biz/role.py
> fix: update role user not exist

- saas/backend/biz/application_process.py
- saas/backend/biz/role.py
> Fix role user not exist

- frontend/src/App.vue
- frontend/src/components/infinite-tree/index.vue
- frontend/src/views/group/components/iam-add-member.vue
- frontend/src/views/my-manage-space/add-member-boundary/index.vue
feature: 优化组织架构人员选择器隐藏已选数量为0的type
> feature: 优化组织架构人员选择器隐藏已选数量为0的type

- frontend/src/components/choose-ip/topology-tree.vue
feature: 增加直接选择父级数据，子集table的checkbox的disabled状态下增加tooltip
> feature: 增加直接选择父级数据，子集table的checkbox的disabled状态下增加tooltip

- frontend/src/App.vue
> fix:  处理跑马灯组件数据为空的情况

- frontend/src/App.vue
> fix: 默认回调开关为true

- frontend/src/App.vue
> fix: 修改通知api地址为绝对路径

- saas/backend/biz/application_process.py
> fix: fix default instance approver

- saas/backend/api/management/constants.py
- saas/backend/api/management/v2/filters.py
- saas/backend/api/management/v2/serializers.py
- saas/backend/api/management/v2/urls.py
- saas/backend/api/management/v2/views/__init__.py
- saas/backend/api/management/v2/views/group.py
- saas/backend/api/management/v2/views/subject_template.py
- saas/backend/apps/group/views.py
- saas/resources/apigateway/bk_apigw_resources_bk-iam.yaml
- saas/resources/apigateway/docs/zh/v2_management_add_group_members.md.j2
- saas/resources/apigateway/docs/zh/v2_management_delete_group_members.md.j2
- saas/resources/apigateway/docs/zh/v2_management_grade_manager_list_subject_templates.md.j2
> feat: add management grade manager subject template list api

- saas/backend/common/middlewares.py
> fix: update profiler start prefix

- saas/backend/api/management/v2/views/group.py
> fix: update managemnet group member add template

- frontend/src/views/group/add-perm/index.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/group/components/render-resource.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/render-instance-table.vue
- frontend/src/views/perm-template/edit/sync.vue
fix: 修复用户组—>添加组权限个别实例path数量不同步，导致出现提示层级链路列表不能为空
> fix: 修复用户组—>添加组权限个别实例path数量不同步，导致出现提示层级链路列表不能为空

- saas/backend/api/management/v2/views/group.py
- saas/config/default.py
> Fix managment api

- saas/backend/apps/group/serializers.py
- saas/backend/apps/group/urls.py
- saas/backend/apps/group/views.py
- saas/backend/apps/role/filters.py
- saas/backend/apps/role/serializers.py
- saas/backend/apps/role/urls.py
- saas/backend/apps/role/views/__init__.py
- saas/backend/apps/role/views/group_member.py
- saas/backend/apps/user/serializers.py
- saas/backend/biz/role.py
- saas/backend/common/serializers.py
> feat: add role group member batch action api

- saas/backend/apps/group/urls.py
- saas/backend/apps/role/serializers.py
- saas/backend/apps/role/urls.py
- saas/backend/apps/role/views/group_member.py
> fix: update role group members api

- saas/backend/api/application/urls.py
- saas/backend/api/application/views.py
- saas/backend/api/management/v1/views/group.py
- saas/backend/api/management/v2/views/group.py
- saas/backend/apps/organization/urls.py
- saas/backend/apps/organization/views.py
- saas/backend/biz/utils.py
> feat: add some api

- saas/backend/apps/role/views/group_member.py
> fix: fix role group member department group api (#2518)

- saas/backend/apps/role/views/group_member.py
> fix: update role group member subject group api (#2520)

- saas/backend/biz/subject_template.py
> fix: update get_user_departments (#2522)

- frontend/src/router/index.js
- frontend/src/views/group/add-perm/index.vue
- frontend/src/views/group/components/add-group-perm-sideslider.vue
- frontend/src/views/group/create/index.vue
- frontend/src/views/perm-template/edit/sync.vue
> fix:  修复蓝盾内嵌页面部分二级管理员role_id错误

- saas/backend/api/management/v2/serializers.py
> feat: add managment group list api subject_template_count field

- saas/backend/api/management/v2/serializers.py
> feat: add managment group list api subject_template_count field (#2532)

- saas/backend/api/application/urls.py
- saas/backend/api/application/views.py
> fix: update open api application detail api

- saas/backend/api/application/urls.py
- saas/backend/api/application/views.py
> fix: update open api application detail api (#2539)

- frontend/src/App.vue
- frontend/src/views/user-org-perm/components/group-perm-table.vue
- frontend/src/views/user-org-perm/components/join-user-group-table.vue
- frontend/src/views/user-org-perm/components/left-layout.vue
- frontend/src/views/user-org-perm/components/user-group-table.vue
- frontend/src/views/user-org-perm/user-org-perm.css
> fix: 修复遗留问题

- saas/resources/apigateway/docs/zh/application_detail.md.j2
> fix: fix doc url

- frontend/src/components/choose-ip/topology-tree.vue
- frontend/src/views/perm-template/index.vue
fix: 修复ip选择器只支持单选场景下右侧表格还有可以勾选
> fix: 修复ip选择器只支持单选场景下右侧表格还有可以勾选

- saas/backend/apps/group/views.py
> fix: update group batch member renew

- saas/backend/apps/group/views.py
> Fix group batch renew

- frontend/src/views/user-org-perm/components/join-user-group-slider.vue
> fix: 修改批量加入用户组成员接口

- frontend/src/components/render-resource/compare-detail.vue
- frontend/src/components/render-resource/detail.vue
- frontend/src/components/render-resource/edit.vue
- frontend/src/views/grading-admin/components/render-resource.vue
- frontend/src/views/group/components/render-resource.vue
- frontend/src/views/manage-spaces/components/render-resource.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/render-resource.vue
- frontend/src/views/perm-apply/components/render-resource.vue
- frontend/src/views/perm-template/components/render-resource.vue
- frontend/src/views/resource-permiss/components/render-resource.vue
- frontend/src/views/tempora-perm-apply/components/render-resource.vue
> fix: 测试手动输入选项无法展示

- frontend/src/components/choose-ip/grade.vue
- frontend/src/components/choose-ip/grade/index.vue
- frontend/src/components/choose-ip/index.vue
- frontend/src/components/choose-ip/topology-manual-input.vue
> fix: 修复手动输入查询资源实例type参数错误

- frontend/src/css/mixins/custom-table-dot.css
> fix: 添加漏缺的css公共文件

- frontend/src/components/choose-ip/topology-manual-input.vue
> fix: 修改批量类型字段去重取值

- frontend/src/components/choose-ip/topology-manual-input.vue
- frontend/src/views/group/components/iam-add-member.vue
> fix: 不同层级的资源类型改为由用户自己手动筛选

- frontend/src/components/choose-ip/topology-tree.vue
> fix: 处理只有一条数据且只有一层默认展开后，勾选会位移

- frontend/src/views/grading-admin/index.vue
- frontend/src/views/my-manage-space/index.vue
> fix:  管理空间固定列表格无法点击指定区域编辑

- frontend/src/components/custom-perm-system-policy/index.vue
- frontend/src/views/user-org-perm/components/multi-type-group-perm.vue
- frontend/src/views/user-org-perm/components/right-layout.vue
fix: 多个不同方式加入的用户组权限点击分页会把当前已展开项收起
> fix: 多个不同方式加入的用户组权限点击分页会把当前已展开项收起

- frontend/src/components/header-nav/index.vue
- frontend/src/views/group/components/member-table.vue
> feature: 用户组成员列表添加备注原因

- saas/backend/apps/role/tasks.py
- saas/backend/apps/user/tasks.py
> fix: fix expired_at_before

- saas/config/celery_app.py
> fix: fix init permission_expire_remind task

- saas/backend/biz/action.py
- saas/backend/service/action.py
- saas/backend/service/models/action.py
> feat: query default action sensitivity from backend

- saas/poetry.lock
- saas/pyproject.toml
- saas/requirements.txt
- saas/requirements_dev.txt
> build: update requirements

- frontend/src/views/group/components/group-member-template-detail-table.vue
fix: 用户组详情—>人员模板详情列表搜索场景下增加前端自定义分页
> fix: 用户组详情—>人员模板详情列表搜索场景下增加前端自定义分页

- saas/backend/account/views.py
- saas/backend/apps/approval/views.py
- saas/backend/apps/role/constants.py
- saas/backend/apps/role/views/permission_audit.py
> feat: system manager add manger action permission

- saas/backend/api/management/v2/serializers.py
- saas/backend/api/management/v2/views/group.py
- saas/backend/biz/role.py
> feat: manager group list api add only_inherit param

- frontend/src/views/approval-process/index.vue
- frontend/src/views/group/components/attribute.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/attribute.vue
- frontend/src/views/perm-apply/components/attribute.vue
- frontend/src/views/perm-template/components/attribute.vue
- frontend/src/views/resource-permiss/components/attribute.vue
- frontend/src/views/tempora-perm-apply/components/attribute.vue
- frontend/src/views/user-org-perm/components/group-perm-table.vue
- frontend/src/views/user-org-perm/components/join-user-group-table.vue
- frontend/src/views/user-org-perm/components/left-layout.vue
- frontend/src/views/user-org-perm/components/right-layout.vue
- frontend/src/views/user-org-perm/components/user-group-table.vue
> fix: 修复全平台关于属性条件无法下拉加载问题

- frontend/src/store/index.js
> fix: 敏感等级菜单移动到设置模块下

- frontend/src/store/modules/renewal-notice.js
> fix: 提交漏缺的续期api文件

- frontend/src/components/nav/index.vue
- frontend/src/views/group/components/attribute.vue
- frontend/src/views/group/components/iam-add-member.vue
- frontend/src/views/manage-spaces/components/add-action-side-slider.vue
- frontend/src/views/manage-spaces/components/render-instance-table.vue
- frontend/src/views/my-manage-space/add-member-boundary/index.vue
- frontend/src/views/resource-permiss/index.vue
> fix: 添加漏缺的用户组模块属性下拉菜单

- frontend/src/views/perm/group-perm-renewal/index.vue
feature: 用户组续期页面初始化时自动勾选每个用户组下的人员模板
> feature: 用户组续期页面初始化时自动勾选每个用户组下的人员模板

- saas/resources/templates/group_expired_mail.html
- saas/resources/templates/user_expired_mail.html
feature: 续期邮件通知模板增加过期成员、管理空间、资源实例等数据展示
> feature: 续期邮件通知模板增加过期成员、管理空间、资源实例等数据展示

- saas/poetry.lock
- saas/requirements.txt
- saas/requirements_dev.txt
> fix: update sentry sdk

- frontend/src/components/choose-ip/index.vue
- frontend/src/views/perm-apply/apply-join-user-group/index.vue
[fix: 测试反向资源拉取不同父级下相同id数据会存在数据丢失情况](https://github.com/TencentBlueKing/bk-iam-saas/commit/3385d273fe77020109acb0bacfa15e8a8bcceb6f)
> fix: 测试反向资源拉取不同父级下相同id数据会存在数据丢失情况

- frontend/src/components/choose-ip/index.vue
> fix: 处理type为空的情况

- frontend/src/components/choose-ip/grade.vue
- frontend/src/components/choose-ip/grade/index.vue
- frontend/src/components/choose-ip/index.vue
fix: 修复全平台ip选择器不同拓扑下相同类型的子集数据会被去重遗漏
> fix: 修复全平台ip选择器不同拓扑下相同类型的子集数据会被去重遗漏

- frontend/login_success.html
- frontend/package.json
- frontend/src/App.vue
- frontend/src/api/index.js
- frontend/src/components/auth/index.vue
- frontend/src/components/header-nav/index.vue
- frontend/src/views/group/components/member-table.vue
feature: 测试小窗登录由iframe方式变更为window.open
> feature: 测试小窗登录由iframe方式变更为window.open

- frontend/src/api/index.js
> fix: 修改回调地址

- frontend/src/components/choose-ip/grade/index.vue
- frontend/src/components/choose-ip/index.vue
fix: 修复资源实例ip选择器多层级输入关键词进行搜索返回的数据有缺失
> fix: 修复资源实例ip选择器多层级输入关键词进行搜索返回的数据有缺失

- saas/backend/biz/helper.py
> fix: fix get_user_expired_groups_policies

- frontend/src/components/header-nav/index.vue
- frontend/src/components/header/index.vue
feature: 退出登录重定向地址增加is_from_logout字段
> feature: 退出登录重定向地址增加is_from_logout字段

- frontend/src/IframeEntry.vue
> fix: 调整iframe嵌套页面样式

- saas/resources/templates/group_expired_mail.html
- saas/resources/templates/user_expired_mail.html
> fix: 邮件模板表格文字修改

- frontend/src/IframeEntry.vue
- frontend/src/main.js
- frontend/src/views/perm/index.vue
> fix: 修改iframe样式

- frontend/src/views/perm/components/render-renewal-table.vue
> fix: 去掉mock数据

- saas/backend/apps/role/tasks.py
- saas/backend/apps/user/tasks.py
> fix: update email notification source

- saas/backend/api/application/serializers.py
- saas/backend/api/application/urls.py
- saas/backend/api/application/views.py
- saas/backend/biz/policy.py
- saas/backend/trans/open_application.py
> fix: resolve disussion

- frontend/src/views/perm-apply/apply-custom-perm/index.vue
> fix: 修复自定义权限切换系统未清空资源实例表格数据

- frontend/src/views/resource-permiss/components/member-perm-table.vue
[fix: 调整资源实例表格样式](https://github.com/TencentBlueKing/bk-iam-saas/commit/9c1fcc6867de0e3879978d4ddef4c4697296e982)
> fix: 调整资源实例表格样式

- frontend/package.json
- frontend/src/IframeEntry.vue
- frontend/src/common/util.js
- frontend/src/main.js
- frontend/src/router/ce.js
- frontend/src/router/ee.js
- frontend/src/router/ieod.js
- frontend/src/router/index.js
- frontend/src/store/index.js
- frontend/src/views/group/detail/group-perm-new.vue
- frontend/src/views/manage-spaces/secondary-manage-space/create/index.vue
- frontend/src/views/perm/index.vue
fix: 编辑用户组权限-修改资源实例内容后取消，资源实例内容没有显示为原始的数据，需要刷新页面
> fix: 编辑用户组权限-修改资源实例内容后取消，资源实例内容没有显示为原始的数据，需要刷新页面

- frontend/src/App.vue
feature: 更新跳转链接为7.0以上的蓝鲸版本文档链接
> feature: 更新跳转链接为7.0以上的蓝鲸版本文档链接

- frontend/build/paas-server.js
- frontend/index.html
- frontend/package.json
- frontend/src/App.vue
- frontend/src/components/footer/index.vue
- frontend/src/components/header-nav/index.vue
- frontend/src/store/index.js
- frontend/src/store/modules/global-config.js
> feature: 平台信息使用远程配置

- saas/backend/common/vue.py
- saas/config/default.py
> feat: 支持全局配置商标&LOGO等信息 #2712

- frontend/index.html
> fix:去掉多余引号

- frontend/index.html
- frontend/src/css/mixins/attribute.css
- frontend/src/views/grading-admin/components/render-resource.vue
- frontend/src/views/group/components/attribute.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/attribute.vue
- frontend/src/views/perm-apply/components/attribute.vue
- frontend/src/views/perm-template/components/attribute.vue
- frontend/src/views/resource-permiss/components/attribute.vue
- frontend/src/views/tempora-perm-apply/components/attribute.vue
feature: 兼容dbm系统依赖cmdb平台个别自定义属性集需要展示人员选择器组件
> feature: 兼容dbm系统依赖cmdb平台个别自定义属性集需要展示人员选择器组件

- frontend/index.html
> fix: 修改url

- frontend/src/store/modules/global-config.js
> fix: 修改appcode为固定值

- frontend/src/components/header-nav/index.vue
- frontend/src/store/modules/global-config.js
> fix: 修改兼容远程全局配置项

- frontend/src/css/mixins/iam-add-action-slider.css
- frontend/src/views/grading-admin/components/add-action-sideslider.vue
- frontend/src/views/group/common/render-detail.vue
- frontend/src/views/group/components/add-action-sideslider.vue
- frontend/src/views/manage-spaces/components/add-action-side-slider.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/add-action-sideslider.vue
- frontend/src/views/perm/components/render-detail.vue
[fix: 修复添加系统和操作搜索框未铺满问题](https://github.com/TencentBlueKing/bk-iam-saas/commit/9adbc5a4854cab0fa7a9bfae2de6575db65b9558)
> feature: 统一平台添加系统和操作侧边栏页面排版

- frontend/src/views/user/index.css
[fix: 用户模块添加拖拽样式](https://github.com/TencentBlueKing/bk-iam-saas/commit/34a73753d12704c9e10f0d4eeebe3a824065b627)
> fix: 用户模块添加拖拽样式

- frontend/src/common/constants.js
- frontend/src/components/choose-ip/sideslider.vue
- frontend/src/components/nav/index.vue
- frontend/src/router/index.js
- frontend/src/views/audit/index.vue
- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/group/add-perm/index.vue
- frontend/src/views/group/clone/index.vue
- frontend/src/views/group/components/basic-info.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/group/create/index.vue
- frontend/src/views/manage-spaces/components/render-instance-table.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/render-instance-table.vue
- frontend/src/views/manage-spaces/secondary-manage-space/create/index.vue
- frontend/src/views/perm-apply/components/resource-instance-table.css
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/tempora-perm-apply/components/resource-instance-table.css
- frontend/src/views/user-org-perm/components/multi-type-group-perm.vue
> fix: 修复7-24版本体验问题

- frontend/src/components/nav/index.vue
- frontend/src/views/perm/components/render-detail-edit.vue
Fixes #(issue)
·修复自定义权限查看实例资源组件有多个资源类型tab项时无法删除实例
> fix: 自定义权限查看实例资源组件有多个资源类型tab项时无法删除实例

- saas/resources/apigateway/bk_apigw_resources_bk-iam.yaml
> feat: add endpoint to apigw resources #2760

- frontend/build/paas-server.js
- frontend/index.html
- frontend/package.json
- frontend/src/common/util.js
- frontend/src/components/header-nav/index.vue
- frontend/src/language/lang/en.js
- frontend/src/model/policy.js
- frontend/src/model/related-resource-types.js
- frontend/src/store/modules/global-config.js
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
Fix #(issue)
·升级magicbox组件库版本(修复配置化表格hover全选按钮会丢失填充背景色)
.完成年度测试提出的优化修改
> feature: 升级magicbox组件库版本

- saas/backend/healthz/views.py
> feat(heathz): remove detection of usermgr api

- frontend/package.json
- frontend/src/components/header-nav/index.vue
- frontend/src/store/modules/global-config.js
feature: 升级全局配置plugin，区分title和productName之间的文本差异
> feature: 升级全局配置plugin，区分title和productName之间的文本差异

- frontend/src/views/my-perm/components/custom-perm-policy.vue
- frontend/src/views/my-perm/components/custom-perm-table.vue
- frontend/src/views/my-perm/components/multi-type-group-perm.vue
- frontend/src/views/my-perm/components/render-renewal-table.vue
- frontend/src/views/my-perm/components/right-layout.vue
- frontend/src/views/my-perm/perm-renewal/index.vue
- frontend/src/views/transfer/index.vue
[fix: 处理清空任意搜索搜索条件后回显跨系统全选激活态](https://github.com/TencentBlueKing/bk-iam-saas/commit/dbb3d80347ac82c15c9861230496cb99f332e9cf)
[fix: 修复多类型跨系统删除时无法自动匹配跨系统checkbox是否可勾选](https://github.com/TencentBlueKing/bk-iam-saas/commit/a7f7fed908d42ee3bf4bde6b7b5a9406ba865733)
> fix: 修复多类型跨系统删除时无法自动匹配跨系统checkbox是否可勾选

- frontend/src/store/index.js
- frontend/src/views/group/components/iam-add-member.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/iam-add-member.vue
- frontend/src/views/my-manage-space/add-member-boundary/index.vue
fix: 用户组详情—>蓝盾内嵌手动输入选项卡页面隐藏跳转到授权边界入口
> fix: 用户组详情—>蓝盾内嵌手动输入选项卡页面隐藏跳转到授权边界入口

- frontend/src/components/header-nav/index.vue
fix: 兼容需要encodeURIComponent才能转义的特殊字符
> fix: 兼容需要encodeURIComponent才能转义的特殊字符

- saas/resources/apigateway/bk_apigw_resources_bk-iam.yaml
> fix: apgw resource yaml

- frontend/index.html
- frontend/src/common/util.js
- frontend/src/router/ce.js
- frontend/src/router/ee.js
- frontend/src/router/ieod.js
[fix: 兼容容器化部署外部环境非根路径的path](https://github.com/TencentBlueKing/bk-iam-saas/commit/b6390bfc0db0d5441c62eb13c0ced5fa4750686e)
> fix:  兼容容器化部署外部环境非根路径的path

- frontend/src/views/group/components/add-group-perm-sideslider.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/add-group-perm-sideslider.vue
- frontend/src/views/my-manage-space/add-member-boundary/index.vue
- frontend/src/views/perm-apply/apply-join-user-group/index.vue
fix: 优化蓝盾添加人员内嵌页面获取组织架构接口调用多次
fix:  我的权限非资源实例搜索增加系统筛选(https://github.com/TencentBlueKing/bk-iam-saas/issues/2794)
feature: 去掉组权限权限模板刷新icon(https://github.com/TencentBlueKing/bk-iam-saas/issues/2795)
> fix: 优化蓝盾添加人员内嵌页面获取组织架构接口调用多次

- frontend/src/views/group/components/add-group-perm-sideslider.vue
feature:  用户组—>组权限添加权限模板去掉刷新icon
> feature:  用户组—>组权限添加权限模板去掉刷新icon

- frontend/src/components/choose-ip/grade/index.vue
- frontend/src/components/choose-ip/index.vue
- frontend/src/components/choose-ip/topology-tree.vue
fix: 兼容实例视图最后一个节点且当前拓扑层级child_type为空时，不需要请求下一层拓扑数据
> fix: 兼容实例视图最后一个节点且当前拓扑层级child_type为空时，不需要请求下一层拓扑数据

- frontend/src/components/header-nav/index.vue
- frontend/src/views/grading-admin/index.vue
- frontend/src/views/my-manage-space/index.vue
> fix: 更改7.1版本链接跳转

- frontend/src/components/render-resource/detail.vue
- frontend/src/model/instance.js
- frontend/src/model/related-resource-types.js
- frontend/src/views/group/components/render-instance-table.vue
fix: 修复资源实例详情path数量与count不一致问题
> fix: 修复资源实例详情path数量与count不一致问题

- saas/config/default.py
- saas/poetry.lock
- saas/pyproject.toml
- saas/requirements.txt
- saas/requirements_dev.txt
> fix: add pymysql

- frontend/src/App.vue
- frontend/src/common/util.js
- frontend/src/components/header-nav/index.vue
- frontend/src/views/grading-admin/index.vue
- frontend/src/views/my-manage-space/components/iam-edit/member-selector.vue
- frontend/src/views/my-manage-space/index.vue
- frontend/src/views/set/components/render-super-manager.vue
- frontend/src/views/system-access/complete/index.vue
- frontend/src/views/system-access/index.vue
- frontend/src/views/user/components/record-list.vue
> feature: 更新所有文档中心跳转链接最新规范

- frontend/src/components/choose-ip/grade/index.vue
- frontend/src/components/choose-ip/index.vue
fix: 修复child_type取值错误导致无法展开非最后一个节点拓扑
> fix: 修复child_type取值错误导致无法展开非最后一个节点拓扑

- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/group/components/preview-resource-dialog.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/manage-spaces/components/render-instance-table.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/render-instance-table.vue
> fix: 修复用户组无资源实例和属性条件时预览差异对比报错

- frontend/src/views/my-manage-space/components/iam-edit/member-selector.vue
fix: 修改member-seletor下display_name的展示条件
> fix: 修改member-seletor下display_name的展示条件

- frontend/src/views/grading-admin/components/render-instance-table.vue
- frontend/src/views/group/components/render-instance-table.vue
- frontend/src/views/manage-spaces/components/render-instance-table.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/render-instance-table.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/tempora-perm-apply/components/resource-instance-table.vue
fix: 修复主操作存在关联操作且接口响应数据为空时，表格关联操作数据会被置空
> fix: 修复主操作存在关联操作且服务器数据异常时，表格关联操作数据会重新渲染被置空

- frontend/src/views/group/components/render-resource.vue
- frontend/src/views/manage-spaces/components/render-resource.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/render-resource.vue
- frontend/src/views/perm-template/components/render-resource.vue
fix: 处理只有自定义属性无资源实例的授权范围时提示undefined问题
> fix: 处理只有自定义属性无资源实例的授权范围时提示undefined问题

- frontend/src/views/group/components/member-table.vue
> fix: 蓝盾侧需求协调参数归一化

- frontend/src/common/constants.js
- frontend/src/components/nav/index.vue
- frontend/src/views/manage-spaces/authorization-boundary/edit/first-level.vue
feature: 切换管理员身份重定向的页面增加授权边界和二级管理空间
feature: 授权边界直接展示理由字段
> feature: 切换管理员身份重定向的页面增加授权边界和二级管理空间

- saas/backend/common/vue.py
- saas/config/default.py
> feat:蓝盾侧添加成员时限制勾选公司&事业群节点

- frontend/src/views/grading-admin/components/render-member.vue
> feature: 增加需要自定义添加授权人员边界样式的路由

- frontend/src/views/group/components/member-table.vue
> fix: 去掉加入方式（涉及到整个调用链路的修改）

- saas/.importlinter
- saas/backend/audit/audit.py
- saas/backend/audit/signals.py
> fix:修复由于bulk_create不能触发signal，导致的审计日志缺失

- saas/config/default.py
> fix:修复dbm自定义权限审理流转异常

- frontend/src/views/group/components/attribute.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/attribute.vue
- frontend/src/views/perm-apply/components/attribute.vue
- frontend/src/views/perm-template/components/attribute.vue
- frontend/src/views/resource-permiss/components/attribute.vue
- frontend/src/views/tempora-perm-apply/components/attribute.vue
feature: 全平台属性条件搜索增加防抖搜索（处理组件searchLoading持续触发）
> feature: 全平台属性条件搜索增加防抖搜索（处理组件searchLoading持续触发）

- frontend/src/views/group/components/attribute.vue
- frontend/src/views/manage-spaces/secondary-manage-space/components/attribute.vue
- frontend/src/views/perm-apply/components/attribute.vue
- frontend/src/views/perm-template/components/attribute.vue
- frontend/src/views/resource-permiss/components/attribute.vue
- frontend/src/views/tempora-perm-apply/components/attribute.vue
feature: 全平台属性条件搜索增加防抖搜索(处理组件库searchLoading持续触发)
> feature: 全平台属性条件搜索增加防抖搜索(处理组件库searchLoading持续触发)

- saas/config/ce.py
- saas/config/default.py
- MySQL / Redis / Rabbitmq 支持 TLS 配置
> feat: support tls

- frontend/src/views/manage-spaces/components/basic-info-detail.vue
- frontend/src/views/perm-apply/apply-custom-perm/index.vue
- frontend/src/views/perm-apply/components/resource-instance-table.vue
fix: 修复分级管理员进入二级管理空间详情删除管理员异常问题
fix: 修复无权限申请资源实例表格样式问题
fix: 无权限申请下用户组推荐、细粒度权限选项卡增加url页面访问参数，避免刷新页面后丢失参数
> fix: 修复分级管理员进入二级管理空间详情删除管理员异常问题

- frontend/src/views/perm-apply/components/resource-instance-table.css
- frontend/src/views/perm-apply/components/resource-instance-table.vue
- frontend/src/views/tempora-perm-apply/apply-custom-perm/index.vue
- frontend/src/views/tempora-perm-apply/components/resource-instance-table.vue
> fix: 优化无权限申请表格样式，处理临时权限申请聚合去重问题

- frontend/src/components/nav/index.vue
- frontend/src/views/group/components/iam-add-member.vue
>  fix: 我的管理空间需要将upgrade icon 去除
